### ISSUE TITLE
Importer/CMS - audit check and additions

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#104]
Hi @evz I'd like to move towards pulling in more Nigeria data into the CMS and also adding quite a bit of Mexico data as well. I think the easiest way to do this is through the Master Import Sheet we already have up and running.

It would good to start establishing a way to audit the import process so we can see what errors are popping up. @tlongers had a couple of good suggestions on this point that I'll let him spell out below.

Once we have it planned out I'll start adding quite a bit to the Master Import Sheet.

**Comment by tlongers** [comment]
@tonysecurityforcemonitor what are the sources of error you've found? Is it missing values or mixed-up rows, wrongly linked records, formatting stuff?

**Comment by tonysecurityforcemonitor** [comment]
@tlongers The main concern I have right now is missing values - but I could see some of those other errors creeping in (or already in the CMS perhaps) - which are much harder to spot.

**Comment by evz** [comment]
A cast off from running the importer script is a log file that logs out all the rows where the importer has run into problems (and tries to give some kind of context as to what the error was). Since we've shifted over to using the Master Import Sheet, these errors have dropped dramatically. I also gave up on trying to write code to break apart the various ways in which the sources were being entered in the Google Sheet. So, if breaking apart the source field into the various attributes (publication title, publication date, article title, etc) fails, I just insert the contents of the whole field into the source table. This is something that we can come back to eventually and manually break apart (or maybe come up with a more clever way of formatting the sources or pulling out the attributes from those fields in the spreadsheets).

**Comment by tonysecurityforcemonitor** [comment]
@evz - The concern that I'm seeing right now is that it appears that some of the data in the CMS isn't being displayed in the UI - (for instance only some of the Areas of the 1 Mechanised Division are displayed) - and it's not clear where the issue lies - is it an importer issue, a CMS issue or an UI issue?

So three (probably dumb) questions:
1) Are there any errors outstanding that need to be fixed? Have the errors in the Import Sheet that I've fixed been imported after the fix? 
2) Is everything from the Master Import Sheet imported into the CMS?
3) Can I add additional rows for import to the Master Import Sheet?

**Comment by evz** [comment]
@tonysecurityforcemonitor We've talked about this over email and in other issues but I'll recap here (mainly for @tlongers)

I'd love to have to only put minimal effort into maintaining the script that updates the CMS from the Google Spreadsheet and get to the point soon where you are just maintaining the data in the actual CMS. Right now, the script does not really attempt to do anything about things that have gone missing from the spreadsheet mainly because it's kind of a hard problem. The upshot of this is that, in order to have those kind of changes reflected in the CMS / API, I need to flush the database and re-run the import. The import from the spreadsheet currently takes around 20-30 minutes to complete. It takes about as long from a clean database (meaning no data yet imported) as it does from one that already has data in it (meaning, it updates things or doesn't touch them as the case may be). It's also pretty trivial to flush everything without disrupting the data that is served from the API. The only major caveat being that every time you flush, you end up with new UUIDs for the various entities (orgs, people, events). I'd love to be able to promise stable IDs at some point but it doesn't seem super necessary yet. I've created a pretty clean separation between the tables that are used by the CMS and the data that is served through the API. The thinking there was that, at one point, we were talking about doing "releases" of the data and this was an easy way of accomplishing that without having too much extra overhead (and it also vastly improves performance). One caveat is that when you make a change in the CMS, it won't get reflected right away through the API. I can add a button or something that allows you to create a "release" of the data which will, in effect, refresh the data that is served through the public API being consumed by the UI parts right now. But I digress ...

You should be able to add things at will to the spreadsheet and either let me know when you'd like to have it re-imported. As part of setting up the CMS / API on a new server, I imported all of the OSM data that we needed for Nigeria, Mexico, Sierra Leone, Liberia, and Democratic Republic of Congo (the last few because there were organizations based there in the spreadsheet so, why not). That means that things should show up through the UI once it is imported and the API tables refreshed (by creating a "release"). 

I am running the importer script locally again on a clean database and will send over the errors that it encounters (if any). The live CMS / API should be relatively up-to-date. If there are more recent additions that are missing, I can run the import again on the server.

**Comment by tonysecurityforcemonitor** [comment]
@evz I'm trying to check the CMS staging site against what I currently see in the UI - but I'm having trouble logging in...

Also - it looks like only a few of the Mexico entries got into the CMS?

**Comment by evz** [comment]
Agh! One of the consequences of reloading all the data is that I lose the user table, too. I should probably stop doing that. I reloaded the users so you should be able to log in again. It looks like it got 207 organizations for Mexico.

**Comment by tlongers** [comment]
Superceded. Closing.
