### ISSUE TITLE
OSM questions

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#106]
As part of importing OSM data into this application, I create a subset of all OSM data for the target country from which we can draw nodes and relations. The subset I am drawing right now is basically anything that has an `admin_level` tag and where the `name` property is not null. This seemed somewhat reasonable but I am noticing in at least one case the site for a given organization is a hospital which does not have an `admin_level`. (This one: https://www.openstreetmap.org/node/2949153405). Is that something that we will be seeing regularly? Is there a rule that I can use to subset the OSM data? If we are needing all of OSM, we might want a different strategy that loads things as needed instead of trying to load everything up front.

**Comment by evz** [comment]
Oh, that was mainly for @tonysecurityforcemonitor ^

**Comment by tonysecurityforcemonitor** [comment]
@evz Sorry - that was the result of a bad workaround on my side. I'll clean that entry - and any other that you find with a similar issue.

**Comment by evz** [comment]
OK. That was the only one I saw. Does the strategy for subsetting the OSM data seem sane?

**Comment by tonysecurityforcemonitor** [comment]
@evz - yep that strategy sounds right to me. I think we will be able to identify smaller/similarly sized subsets as we get more familiar with OSM data structure.

**Comment by evz** [comment]
OK. Great. I'll close this for now then.

**Comment by tlongers** [comment]
Hrm, an example/question for @evz @tonysecurityforcemonitor ...

Say I want to geocode "Campo Militar Numero 1", as the HQ (```site:geonames_id```) for an organization . At present, we'd  tag this with the nearest ```relation``` tagged with ```admin_level``` which is [Naucalpan de Juárez](http://www.openstreetmap.org/relation/5606080).   However, there's actually a precise entry for this facility in OSM, here:

http://www.openstreetmap.org/way/176021979

But it's a ```way``` not a ```relation``` and it's not tagged as an ```admin_level```. Without breaking everything done do far, Is there a way we can geocode with OSM datapoints that are tagged in this way?

**Comment by evz** [comment]
Yeah. I like the idea of being as precise as possible. The problem is not wanting to load all of the OSM data ahead of time. And the problem with ways is that they are not relations which means that you have to put together a polygon yourself (all you get is a list of nodes that makes up the way). If you guys are interested in this, maybe we could come up with a set of tags that we could use to subset the ways that we create polygons from? I noticed that the way @tlongers referenced above is tagged ["landuse: military"](http://wiki.openstreetmap.org/wiki/Tag:landuse=military?uselang=en-US) and, just a cursory search through the ways that I have from Nigeria shows that there are some barracks that show up tagged ["military: barracks"](http://wiki.openstreetmap.org/wiki/Tag:military=barracks?uselang=en-US). If you follow those links, there seem to be some other useful tags that we could use to import things. I'll go ahead and re-open this and maybe we can discuss a bit further.

**Comment by tonysecurityforcemonitor** [comment]
@evz @tlongers 

I would approach it this way - using the current data structure the full Site should be Headquarters (Barracks, Base, Physical Asset) + (Site OSM Name) + (Admin 1 OSM Name)

In this case it would be Campo Militar Numero 1 (a text only value), Ciudad de México [(link),](http://www.openstreetmap.org/node/62270270) Ciudad de México ([link](http://www.openstreetmap.org/relation/1376330))

I would interpret using the OSM name/data for Campo Militar as the Site Name would result in:

Campo Militar Numbero 1, Ciudad de México ([link](http://www.openstreetmap.org/relation/1376330))

I currently have a bit of a preference towards having a base/headquarters with a proper name being a text value rather than an OSM data point for two reasons: 

1) having a city/village/OSM node and then a state/province/governorate/OSM relation gives more context in the current visualization (and could be helpful in any future visualizations) because its often hard to tell what city a base is in or near if all you have is the name of the base and the state/province/governorate it is in. While the Map does a great deal to help a user make sense of it, in other visualizations that use the same date, like the dossier, that context is lost. 
2) I'm not sure about the consistency of the data across countries - both in terms of OSM and in what we find in the course of our own research. In my mind the current data structure/method works because there will always be a node for a Site and there will always be a relation for the admin_1.

The grains of salt for all of this is that it makes assumptions about users which are untested and it is also influence by the current UI. This is a really good discussion to have we'll keep it going.

**Comment by tlongers** [comment]
The actual name of the facility is ```Campo Mil. No. 1-L, Col. Federal, México, D.F.``` ([from a 2004 source](https://web.archive.org/web/20040209230009/http://www.sedena.gob.mx:80/ejercito/comandancias/imagenes/VIIRM.gif)). However, ```D.F.``` was renamed ```Ciudad de México```. 

@evz Yeah, I saw that too :) We would need to explore further the prevalence and accuracy of the use of tags like ```landuse:military``` and similar. It's clear that ```Campo Mil. No 1-L``` is a primary military facility, and other sources can be found to substantiate this; however, it will be harder  to  state categorically that other sites as you travel down the organisational hierarchy and I'd be more skeptical of an OSM tag for those. I'm also wondering if anyone polices the application of such tags , and if they might be allies. 

@tonysecurityforcemonitor Your suggestion is practical and it doesn't stop us refining location information in the future if we need. However, the two primary time vampires our research method are sourcing and geocoding, however, and we need to look closely at what aspects of these can be helpfully automated. I favour an approach where I click on the thing I want and the tool magically gets all geo we can from whatever systems it can :)

**Comment by tonysecurityforcemonitor** [comment]
@evz @tlongers - yes I think there are other tags for police and other facilities that could prove quite helpful. A very useful line of inquiry.

> we need to look closely at what aspects of these can be helpfully automated. I favour an approach where I click on the thing I want and the tool magically gets all geo we can from whatever systems it can :)

Agreed! It may be that we end up capturing more data automatically via a process - for instance if we have a city/node for an organization's Site we don't capture the municipio (OSM admin_level_6 for Mexico) anywhere - it's similar story for Events. That's largely a time vampire based decision rather than method.

**Comment by evz** [comment]
I know that this is not a really super primary focus of this research but something that is somewhat unique about using OSM is that if something is wrong or needs to be enhanced, you are empowered to take action. It would be kind of a nifty cast off of the SFM research to ensure that things are tagged and placed correctly within an administrative hierarchy in Open Street Map (where it makes sense). I dunno, maybe down the road when you have like 100 interns or something ;)

**Comment by tonysecurityforcemonitor** [comment]
@evz Nope its a great point - I've got a running list of needed changes/additions so we'll go down that route one way or another - especially if we have 100 interns :)

**Comment by evz** [comment]
Another way to think about this is whether or not we want a one-to-one relationship between Sites in the monitor and OSM nodes. I suspect we might want a bit more flexibility especially since adding things to OSM and then getting the data back out can take a few ticks.

**Comment by tlongers** [comment]
@evz said:
> It would be kind of a nifty cast off of the SFM research to ensure that things are tagged and placed correctly within an administrative hierarchy in Open Street Map.

I did an assessment of the accuracy of the OSM Mexico administrative info, as compared with that officially released and found 3 errors (which is a pretty good vote of confidence in OSM, tbh). I'll  feed those back to the team that did that import. Longer run, the more of SFM information that OSM, Wikipedia, Wikidata and other big chunks of the net hold, the better. I good start would be to see if there is a interest within OSM's communities in creating a loose conspiracy around the geographies of security forces and how to accurately describe, class and tag them because it looks quite haphazard.

**Comment by tlongers** [comment]
@evz  said:
> I suspect we might want a bit more flexibility especially since adding things to OSM and then getting the data back out can take a few ticks.

Do you mean that we might use OSM create a new node for a particular feature we'd like to see in the map, and then bring that back the data into the SFM application?

**Comment by evz** [comment]
@tlongers Yeah, I guess that's what I was getting at. That's based on an admittedly naive understanding of how "the map" gets updated and redistributed. But, if there's an opportunity for a closer collaboration with OSM in general, maybe that could be streamlined a bit. We have a friend on the OSM board who might be able to point us in the right direction when we get to that point.

**Comment by tlongers** [comment]
Interesting issue, but is more methodological and organizational than technical now. Technical work on Locations app now (Sept 2018) draws OSM objects in as needed. Closing.
