### ISSUE TITLE
Add form validation to allow for fuzzy dates

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#114]
@evz @tonysecurityforcemonitor  Check this entry:

http://ffctn.com/clients/on/sfm/M27/#country/mx/o/f74a7c67-c416-4621-8430-a2f1b5f198c9!date=2009-08-03&focus=chart

43 Batallón de Infantería has 21 Zona as a parent from 1905 onwards, which isn't correct. First date is just ```2010``` in the source data:

https://docs.google.com/spreadsheets/d/1rOOFZ_EolAHw07EeYSl8fKHpnR5K6ubJ5BICXj83Vq4/edit#gid=0&range=1643:1643

What does the importer do if it finds a date value that is not ```MM-DD-YYYY```?

**Comment by tonysecurityforcemonitor** [comment]
blarg! - thanks @tlongers - Google Sheets formatting issue here - will fix.

**Comment by tonysecurityforcemonitor** [comment]
The importer should be able to handle dates that are just the year or the month and year, right @evz?

**Comment by evz** [comment]
Yeah, it'll just normalize it as January 1st of that year. If you'd like a different default behavior, let me know.

**Comment by tonysecurityforcemonitor** [comment]
@evz - ah ok... and I'm assuming if its MM YY it would be normalized to the 1st of that month... Ideally we'd like dates to be able to remain fuzzy so that they can be fuzzy the UI and eventual export of the data as well - otherwise we are speaking with more accuracy that we actually have.

Hmmm - would implementing something different at this point mess up the UI as it is currently realized? We do need to fix this, it's just a question of when...

**Comment by evz** [comment]
One way to do this is to just store the date along with a measure of the date's accuracy. That would give us a way to include them in queries based upon how accurate they are and also reconstitute them in their appropriate way. 

It'll probably take a bit of effort to implement something like this at this point. If it's OK, I think we might want to put a bit more thought into what we expect the behavior to be (so, for example, what does this do to ranges of dates and how do we compare those ranges to one another) and then shoot for adding in true fuzziness at a later point.

**Comment by tlongers** [comment]
@jeancochrane I'm bumping this thread up as it seems relevant now. How do we enter fuzzy dates (for example, when we have just ```YYYY-MM``` rather than ```YYYY-MM-DD```) in the data entry wizard, and how is the backend set up to handle these?

**Comment by jeancochrane** [comment]
@tlongers Great point, thanks for flagging this. Since dates get submitted as text strings through the form, you should be able to delete portions of the date string (like `MM` or `DD`) via keyboard. Is that good enough, or do you think we need a friendlier interface?

We haven't wired up the form validation with fuzzy dates in mind, so it probably won't work just yet, but let's add it to the priority board. Shouldn't be too much bother since the models on the backend are already using `ApproximateDateFields`, it'll just be a matter of telling the form to anticipate them.

**Comment by tlongers** [comment]
@jeancochrane deleting portions of the date is fine (sorry for delayed response). Added high priority label on this as it's a long running niggle.

**Comment by jeancochrane** [comment]
Great, thanks for tagging this @tlongers! Easier to keep track of.

**Comment by jeancochrane** [comment]
Do you think this needs to be part of the launch Milestone @tlongers? I'm fixing the lack of fuzzy dates in the importer in #246, but seems like this is related to the data entry wizard.

**Comment by tlongers** [comment]
Good point. We also input dates in the General Filters sidebar on search results - will it handle fuzzy date there?

**Comment by jeancochrane** [comment]
That's a great question. I think it deserves its own issue. How does #277 look?

**Comment by tlongers** [comment]
:) good. Keeping this issue open though pending resumption of work on the data entry side.

**Comment by tlongers** [comment]
Closing - this was resolved in #277.
