### ISSUE TITLE
Source storage structure

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#122]
@evz can you point me to the storage structure used for sources?

**Comment by evz** [comment]
Do you mean the table structure?

**Comment by tlongers** [comment]
Yes please.

**Comment by evz** [comment]
![organization](https://cloud.githubusercontent.com/assets/551491/26253897/72cb66b6-3c7a-11e7-87a8-b09b3e9962fd.png)

So, this is an extremely abbreviated diagram showing just the attributes of an organization (without the related tables like `MembershipOrganization`, `Area`, `Site`, etc.)

The basic concept is that each attribute of an entity is actually stored in it's own table. So, for instance if you look at the `OrganizationName` property, it's got an `id` (which is just that particular name's primary key on that table) an `object_ref` (which is a reference to the overarching `Organization` table), a `confidence` and a `language`. Missing from the diagram are the tables that sit between each attribute and a reference to it in the `Source` table. If you follow the little line that connects the `OrganizationName` table to the `Source` table you'll see something that says `sources (organization_organizationname_related)` which is just a table that has two columns: one for a reference to a source and one for a reference to the attribute that is described in the source (this is because we only want one reference to a source but it can refer to many attributes of things and attributes of things can have many sources (a so-called "many-to-many" relationship)). 

For attributes that can contain many values per `Organization`, we have another related table that actually stores those values. So, for instance with an organization's aliases, we'll want a single organization to refer to many aliases (a "one-to-many" relationship). In the diagram if you find the `OrganizationAlias` table, you'll notice that there is a reference from that table to the `Alias` table (which is where the "many" aliases are actually stored). 

While seemingly overly complex, this structure has many benefits that let us represent your spreadsheets pretty accurately. However, it does lead to some rather burdensome performance overhead. In order to get the API to work at all, I had to create flattened versions of these super-normalized entities that I could then use in the API responses. (see for example the way that the flattened `organization` (with sources) [table is created](https://github.com/security-force-monitor/sfm-cms/blob/master/sfm_pc/management/commands/sql/organization_sources_view.sql). Imagine having to perform that query every time you wanted to fetch a single organization from the database. Now imagine multiplying the complexity of that by also getting all the areas, sites, member organizations, associated people, etc (see for instance the query to get all information about a [single organization](https://github.com/security-force-monitor/sfm-cms/blob/master/api/views.py#L443-L472). All of those `LEFT JOIN` bits are referring to other flattened tables like the one that I linked to above for `organization`) Those flattened tables are pretty much essential but it would be great to also have a way to reduce that complexity a bit eventually. I have a few ideas but I think that's probably a discussion for another time.

OK, this got a little bit tangential. Hopefully it's useful info.

**Comment by tlongers** [comment]
Thanks for the thorough response; very useful. 

I was probing the extent to which our source format relates to [Dublin Core](http://dublincore.org/documents/dces/) and [other bibliographic formats](https://www.zotero.org/support/dev/data_formats), considering if there are  low-hanging things we can do to improve overall interoperability of our dataset (a mid-importance issue emerging from the user research).  No conclusions reached yet :)
