### ISSUE TITLE
Make sure OSM features are only unique when ID + type are unique

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#131]
As @tlongers pointed out in #130, OSM IDs are only unique within the realm of a particular feature type. When we import OSM data let's implement some logic that only considers each feature unique if it's OSM ID and feature type (so, node, relation, etc) are unique.

**Comment by tlongers** [comment]
Bumping this up.

**Comment by jeancochrane** [comment]
OK to push this off to the next chunk @tlongers? According to @evz, this shouldn't pose an issue until we start bringing in more countries.

**Comment by tlongers** [comment]
That's fine.

**Comment by tlongers** [comment]
@evz We're adding 5 more countries shortly; is your assessment of this issue still the same as in Oct 2017?

**Comment by tlongers** [comment]
@jeancochrane There's a new dimension to the old question of whether OSM object id numbers are unique. Following the [link to OSM forum discussions](https://help.openstreetmap.org/questions/2259/is-there-a-reason-why-osm2pgsql-produces-negative-osm_id-values#answer-container-2260) referenced in your fix to #611 (regarding negative OSM object IDs), it seems that there can be situations where OSM objects IDs are not unique. One commenter says:

>osm_id is not unique in osm2pgsql's tables. Long ways are split by osm2pgsql into multiple rows with the same osm_id and multipolygons with distinct areas are also split into multiple rows.

If we're parsing long ways and using them in the platform, are we likely to encounter situations where either:

A) multiple lines/shapes covering different areas appear in the platform with the same ID; or,
B) parts of a multi-part way are purged, because (perhaps) somewhere in the OSM data import and processing pipeline any duplicate OSM ids are filtered out as errors.

What's your take on this?

**Comment by jeancochrane** [comment]
This is a great question that I don't have a super confident answer to. I've never heard of "long ways" before -- best I can surmise from a cursory search is that they're ways that contain more than 1,900 nodes but fewer than the OSM limit of 2,000 ([reference](https://wiki.openstreetmap.org/wiki/OSM_Inspector/Views/Geometry#Layers)). I'm not sure how often we should expect them in our data.

One thing that I can say for certain is that it doesn't seem like these duplicate IDs exist in our current dataset. According to `import_osm.py`, we're only importing shapes from the osm2pgsql tables `planet_osm_point` and `planet_osm_polygon`, as well as the PBF files that we import into `osm_boundaries`. The only table that has duplicate IDs is `planet_osm_polygon`, and all of them are negative:

```
sfm=# select osm_id, count(osm_id) from planet_osm_polygon group by osm_id having count(osm_id) > 1;
  osm_id  | count
----------+-------
 -7256607 |     2
 -7256606 |     2
 -7256605 |     2
 -7256604 |     7
 -7256603 |     4
 -7256602 |     2
 -7256601 |     5
 -7256600 |     5
 -7256599 |     3
 -7256598 |     4
 -7256597 |     3
 -7256596 |     4
 -7256595 |     3
 -6875625 |     5
 -6082198 |     9
 -5596606 |     2
 -5322991 |     2
 -3973100 |     7
 -3973096 |     2
 -3973069 |     6
 -3969631 |     3
 -2984909 |     2
 -1709600 |     2
(23 rows)
```

To me, this is an indication that currently the only problems with duplicate IDs are posed by negative IDs. This seems like another indication to me that we should filter out negative IDs during our import. We could also improve the import pipeline by raising an error if we run into duplicate IDs, so that we know in the future if we're running into problems with new countries.

**Comment by tlongers** [comment]
Thanks Jean, plenty to ponder here. Let's factor this in our wider consideration of issues related to location and how we should proceed.

**Comment by tlongers** [comment]
Resolved in our overhaul of how we create and import locations: https://github.com/security-force-monitor/sfm-cms/commit/47d228157b12e2efa4a36aa8745144d8f6ae2d23
