### ISSUE TITLE
.pot file ?

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#142]
We'd like to start putting together a Spanish language version of the interface for use in testing. Is there a .pot we can use to be doing this?

**Comment by jeancochrane** [comment]
Not yet, but we could generate one pretty quickly. We were also hoping to try out Rosetta, which is a plugin that lets you do translation through the admin interface [(screenshots here)](http://django-rosetta.readthedocs.io/en/latest/usage.html). How soon do you want to get started?

**Comment by tlongers** [comment]
We can get started immediately with a .pot so  translation moves forward pending the set up of Rosetta.

**Comment by jeancochrane** [comment]
Great! I'll aim to get it set up before our meeting tomorrow.

**Comment by tlongers** [comment]
Cool thanks.

**Comment by jeancochrane** [comment]
Added a Spanish .po file and installed Rosetta in [f764645](https://github.com/security-force-monitor/sfm-cms/commit/f764645f1fd0bfd9fc6c8c3a24e70efe7a8f3c7c).

You can access the translation UI by naviating to `~/rosetta` (note that you don't want `~/en/rosetta`!) It's admin-only by default, but everyone should have the correct privileges. Feel free to give it a spin and refer to [the docs](http://django-rosetta.readthedocs.io/en/latest/usage.html) if you're eager to try it out; otherwise we can talk more about it during our call today.

**Comment by tlongers** [comment]
The file doesn't include terms like ```incident```, ```unit```, ```personnel``` which appear in the front-end. Are these just yet to be wired up into gettext?

**Comment by jeancochrane** [comment]
Yeah, that's planned to be the bulk of the work in the Internationalization portion of the scope. Let's chat today about a good timeline for getting that done.
