### ISSUE TITLE
Person detail: Show chain of command

### ISSUE THREAD

**Issue by reginafcompton** [security-force-monitor/sfm-cms#162]
Show the chain of command in a graphical chart. 

The views already spits out the `chain_of_command` as a JSON object: https://github.com/security-force-monitor/sfm-cms/blob/master/person/views.py#L60

Find a JS library that suits our needs. @jeancochrane - could you make note of the ones you tried without luck?

**Comment by reginafcompton** [comment]
Related #139

**Comment by jeancochrane** [comment]
Libraries I've looked into so far:

| library | pros | cons |
| -------- | -------- | ------- |
[orgChart.js](https://github.com/dabeng/OrgChart) | pretty; comes recommended | requires ES6 or JQuery 3| 
| [google charts](https://developers.google.com/chart/interactive/docs/gallery/orgchart) | simple; widely used | doesn't seem to allow for inverting (i.e. many-parent relationships) out of the box |
| [springy.js](http://getspringy.com/) |  very simple; built-in animations | no documentation |

Another important point is that the charts have to be in a carousel so that we can show changes over time. I was planning on using [flickity](https://flickity.metafizzy.co/) for this (for which @reginafcompton and I both have developer licenses).

**Comment by reginafcompton** [comment]
I've made decent progress on this issue using [vis.js](http://visjs.org/docs/network/index.html). Here's an example of one of the dynamically generated charts:

<img width="644" alt="screen shot 2017-09-01 at 2 57 34 pm" src="https://user-images.githubusercontent.com/13078679/29985932-cfc44618-8f26-11e7-8190-daae6aabb90a.png">

Clearly, I still need to add style, which I can focus on next Tuesday!

**Comment by tonysecurityforcemonitor** [comment]
Thanks @reginafcompton - it's very exciting to see this progress!

**Comment by reginafcompton** [comment]
Deployed on the staging site.
