### ISSUE TITLE
Minimap on site and area maps, for context 

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#170]
Sites and areas displayed on maps in result pages need some context (which country is it in? what area of the country?) What's the overhead/work in putting in a mini-map to the lower-right corner? It should show a zoomed-out view of the map along with a highlight of the area covered in the remainder of the map window ([example](https://codepen.io/jonvadillo/pen/BKMdKx)).

**Comment by jeancochrane** [comment]
I like this a lot! Overhead will probably be determined by whether that library is compatible with our version of Leaflet or not. If so, we can do it pretty quickly; otherwise it'll take a lot of extra code. @reginafcompton is the map whiz, so I'm curious what she thinks.

How do you feel about text for context, as well? Some detail views (e.g. Incidents) show location strings beneath the map, others don't. I couldn't decide whether it was helpful or not.

**Comment by tlongers** [comment]
Cool! 

Text for context is very useful. At a record level, having a label based on ```division-id``` is a must. There is also a temporal aspect to  ```sites``` and ```areas``` in ```organization``` records that are not currently shown.  Currently the maps aggregate this data, but it changes over time. This comes back to whether [the ideas about representing change](https://github.com/security-force-monitor/sfm-cms/wiki/Data-legibility-and-interface-challenges#how-we-can-show-things-that-change-over-time) can be realised.

**Comment by tlongers** [comment]
Skip this. Other fish to fry. Closing.
