### ISSUE TITLE
CMS / Drop down issue when changing language 

### ISSUE THREAD

**Issue by MichelManzur** [security-force-monitor/sfm-cms#181]
If I change the language at any point, the data on the drop downs (Role and Rank) gets erased and I need to type it again.

https://back.securityforcemonitor.org/en/membershipperson/create/

**Comment by jeancochrane** [comment]
This is a good point @reginafcompton -- we don't save form data in cookies when we switch languages. 

I wonder if we can force it to POST to the new URL, which would save the form data? That might be confusing though, since it would also validate the form (and potentially move the user onto the next step).

**Comment by tlongers** [comment]
Refers to earlier version. Closing.
