### ISSUE TITLE
CMS / OSM Name 

### ISSUE THREAD

**Issue by MichelManzur** [security-force-monitor/sfm-cms#182]
While I try to add the OSM name there is more than one option for "Quintana Roo" and the images are broken:

![image](https://user-images.githubusercontent.com/26383493/29936077-ef96fe1e-8e4e-11e7-8cf1-5e34b470e6f4.png)

**Comment by jeancochrane** [comment]
Looks like images were broken because the credentials for the staging site were missing an API key. I added it in [4dd346c](https://github.com/security-force-monitor/sfm-cms/commit/4dd346cfa808833cfdf57424da642cacacab28f3), which should finish deploying in the next 15 minutes, so let me know if images are still appearing to be broken after that.

**Comment by tlongers** [comment]
Closing.
