### ISSUE TITLE
Adding Source - Unit Relationships allow child/parent circle

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#201]
**What I was doing** 
I entered information about two units: the 2 Brigade and the 6 Battalion. When I got to the "Unit Relationships" screen to establish the relationships. The default option for both is "Parent". I hit "Next" without changing anything on the screen. This mean that the 2 Brigade was both the parent and child of the 6 Battalion and vice versa.

![image](https://user-images.githubusercontent.com/18744855/29985054-64de50dc-8f2b-11e7-8d59-9c043785048b.png)

**What I expected**
I thought the system would force me to make one unit the child of the other rather than having them both the children of each other. Ideally, when I make a change - say make the 2 Brigade the parent, it would automatically make the 6 Battalion the child. Similarly, it would be great if the relationship classification also automatically transferred when a change was made.

**Comment by jeancochrane** [comment]
Yup, good call. My plan is:

1. Update form validation to prevent circular relationships (like two orgs being parents of one another)
2. Add some dynamic Javascript to automatically update other relationship types and classifications on a relevant change

I also think that the fields here are pretty confusing. I find myself consistently doing a double-take to try to figure out what the relationship I've entered really means. I think I'll also change the labels here to say:

| | Value |
|-|---------|
| **{Unit name}'s role** | {Parent/child} |
| **{Child/parent} unit** | 6 Batttalion Brigade |
| **Relationship type** | Command |
| **Start and end dates** | {date} {date} |

also using some dynamic code to swap the "{Child/parent} unit" label appropriately.

**Comment by jeancochrane** [comment]
I took care of this in #196 while adding new attributes to the form.

I took a slightly different approach than the comment I left here, but I think it should be more intuitive. Now when we generate forms for defining unit relationships, we only generate as many forms as there are possible unique combinations of the created units. (So if the user created 2 units, we generate 1 form; for 3 units, we generate 3 forms; for 4 units, 6 forms; and so on.) Now each form has a "parent unit" and "child unit" dropdown where the user can select the relevant units. The form does some validation so that it should be impossible to create recursive hierarchies (we check the command hierarchy described by the units in the form, but we also pull the existing hierarchies for any units we know about and double-check to make sure those would look OK if the relationships were to get saved).

Curious to hear what you all think of it!
