### ISSUE TITLE
Datepicker missing I18N

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#235]
Seems possible to get the [datepicker to internationalize](http://bootstrap-datepicker.readthedocs.io/en/latest/i18n.html) - low priority for the moment

**Comment by jeancochrane** [comment]
Internationalization was easy, so I added it to the general search in https://github.com/security-force-monitor/sfm-cms/commit/97e7d043dfa19c9aec20601ddf017e3f9d77c4f5.

Leaving this open, since we need to add it to all the data entry forms too but I don't want to bother right now, but removing from Chunk 1.

**Comment by tlongers** [comment]
Closing. Refers to earlier development.
