### ISSUE TITLE
Importer issues and incorrect display of "Last seen as" information

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#237]
@jeancochrane This may highlight something's up with the importer, so flagging as high priority.

Two issues highlighted by ```~en/person/detail/11/```:

A. "Last seen as" is displaying a value that has no dates, so can't be the last seen. The correct data is that relating to "Inspector y Contralor General del Ejército y Fuerza Aérea" ending 19 January 2013.

B. Duplicate membership entries 

<img width="459" alt="sfm_dashboard" src="https://user-images.githubusercontent.com/2115933/30739456-45d3dea4-9f85-11e7-8dec-561e30e1aa67.png">

**Comment by jeancochrane** [comment]
Great catch @tlongers. I'm sure there are more hidden import problems, so feel free to log problems here as you encounter them.

**Comment by jeancochrane** [comment]
Fixed the "last seen as" bug in [205adc55](https://github.com/security-force-monitor/sfm-cms/commit/205adc55d5605ca0f33a60737a9464cebce700e8).

Seems like one part of this is display problems (when I query those memberships against the database directly I see a similar number of memberships, but different first/last cited dates and role/rank values show up for XI Region Militar that indicate they aren't exact duplicates) and one part is that we're not handling different roles/ranks and gaps in memberships gracefully, related to #238. When a person has multiple roles/ranks/titles within the same unit over the same time period, should we treat those as separate "memberships"? And if so, do we want to display them as separate memberships to the user, or somehow indicate that they're related?

**Comment by tlongers** [comment]
> When a person has multiple roles/ranks/titles within the same unit over the same time period, should we treat those as separate "memberships"? 

Yes, that's right. In the data, changes to the role, rank and title attributes are also given first and last citations.

>And if so, do we want to display them as separate memberships to the user, or somehow indicate that they're related?

Display them as separate to the user.

**Comment by jeancochrane** [comment]
Great. I'll focus on the display issue, then.

**Comment by jeancochrane** [comment]
Memberships that display as duplicates are actually a symptom of #238 (at least in this case). Long storey short, all of the duplicate "XI Region Militar" items in this case come from moments when this person changed rank/role wihiin the unit; we're retrieving the right number of those memberships, but then when we get the membership object by ID to display it in the template, each one defaults to the latest value of the membership since we've been overwriting the object incorrectly.

Closing this in favor of #238, since the other issue (empty brackets in "Last seen as") is closed. If #238 doesn't solve this problem I'll reopen again.
