### ISSUE TITLE
Discontinuous postings and deployments 

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#238]
@jeancochrane In our model, we allow for discontinuous posting and deployment. 

* For a ```person```, this means they may serve with the same organisation for different periods in time. So a person might return to the command of an organization after a period in another organization. 

* For an ```organization```, this means they may be a parent or child of the same organization at different periods in time.  A good example of this is where an organization becomes part of a joint operation, and then rotates out only to return after 3 months. 

We noticed in ```en/organization/detail/7/``` - a very large operation - that these characteristics are not reflected.  However, repeated 502 errors are preventing us from working it out. Can you investigate?

**Comment by jeancochrane** [comment]
Taking a look at this now. IIRC we treat memberships as unique in the code when they involve the same two reference objects (either units or people), in both the import script and the form, so it sounds like we need to adjust that to include first/last cited date as well? Not sure yet what could be causing the errors, but I'll look at the log.

**Comment by jeancochrane** [comment]
Splitting this out into two more issues, to address the 502 errors. #240 reports that there's an improperly set timeout somewhere that prevents request/response cycles longer than 30s, and #239 considers some simple ways of improving the detail views so that we never have to make a user wait longer than 30s anyway.

**Comment by tlongers** [comment]
Thanks for this diagnosis @jeancochrane 

>Taking a look at this now. IIRC we treat memberships as unique in the code when they involve the same two reference objects (either units or people), in both the import script and the form, so it sounds like we need to adjust that to include first/last cited date as well?

I think so. A good example is the discontinuous membership of ```96 Battalón de Infantería``` in ```Operación Conjunta Chihuahua``` which has two slots:

 -  25 August 2008 to 23 November 2008
 -  28 October 2009 to 4 January 2010

Would updating how the database treats first/last cited dates lead to these two stints being rendered as distinct memberships within the front end view tables?

At the point of creating data, how will the system will be able to know that a membership is intended to be unique unless we specify it as such? Let's say we have an initial record that's like this:

```A is a member of B from 1 Jan 1990 to 1 Dec 1990```

We then enter new sources that evidence the below, the date extents to the membership should not change:

```A is a member of B from 1 Feb 1990 to 1 Nov 1990```

If, however, we then find sources that show the following:

``` A is a member of B from 1 Jan 1990 to 1 Feb 1990, and from 1 Nov 1990 to 1 Dec 1990```

Currently, this would lead to no change in the membership and there is no ability within the data entry process to tell the database to treat the period ```1 Feb 1990 to 1 Nov 1990``` as a gap.

If you adapt the way that first/last citations are treated in the context of a membership we have a workaround for the above problem: we just delete the existing record, and re-enter it in two chunks.  However, it's probably more simply fixed by adapting the data entry wizard to enable the user to specify discontinuous periods of membership. 

I'd like @tonysecurityforcemonitor to join in on this to see if I've got it right.

**Comment by jeancochrane** [comment]
My use of "unique" may have been misleading: what I meant to say was that currently when the user records a membership through the data entry wizard, we check to see if a membership relating the person to the specified unit already exists; if it does, we grab it and update it to add the new source and change any values that are different. If the person (or unit, in the case of command hierarchies) left and returned to the membership, we currently override the first membership and replace it with the "returning" one.

The simplest way to fix this, in my view, is to update the logic that checks whether the membership already exists so that it considers the start and end date alongside the person and the unit. If the start/end dates are different, we'll count it as a new membership and make a new record for it. We may also want to use form validation as an opportunity to check for overlap between the two time ranges, and if overlap exists, we can perform an update to widen the range of the existing membership.

Does this make sense? I think we're agreeing, but I want to make sure before I change anything.

**Comment by tlongers** [comment]
Thanks for outlining it so clearly, and for your patience in getting to the core of the issue. My feeble brain needs some set-Tetris to work this out, so here goes:

![data entry - additive membership logic](https://user-images.githubusercontent.com/2115933/30802575-eb367022-a1de-11e7-97bd-f64361f8e59c.png)

The questions I have not figured out an answer for are:
- How do we replace inaccurate data? 
- It's clear how to increase the duration of a membership, but how do we make it smaller? 
- does this logic  handle single first/start or last/end dates that create distinct memberships?

**Comment by jeancochrane** [comment]
@tlongers that set tetris looks great! Exactly what I had in mind, too. I'll go ahead and update the logic that exists for importing data and adding new memberships.

Editing (and replacing inaccurate data in general) is an open question at this point. Let's talk strategies on Thursday and put a plan in place on #138, if that sounds good to you?

**Comment by tlongers** [comment]
Thanks, that works for me.

**Comment by jeancochrane** [comment]
We made some major progress on this in https://github.com/security-force-monitor/sfm-cms/commit/fe6abebc263a6215d0f1ad754110f09382730dc3, but I still have some concerns that there are more parsing errors: in particular, the second deployment for `96 Batallón de Infantería` is missing from the memberships table for [`Operación Conjunta Chihuahua`](https://back.securityforcemonitor.org/en/organization/detail/7/). I'm going to do more sniffing to see what's going on.

**Comment by jeancochrane** [comment]
Turns out it was a display issue and the importer was working as planned. Nice! Fixed the display in https://github.com/security-force-monitor/sfm-cms/commit/1386f2544851a327afa6212c5aa63561df528e6d.

@tlongers, want to verify that all the discontinuous memberships you expect to see are up before I count this as closed?

**Comment by tlongers** [comment]
Paging @tonysecurityforcemonitor on this content

**Comment by tonysecurityforcemonitor** [comment]
@jeancochrane @tlongers - this looks great! The only issue is with the `2 Batallón de Infantería` one of it's memberships from 3 June 2008 to 15 January 2009 is missing, and one of it's memberships on 20 February 2009 is duplicated. Every other discontinous membership is correctly displaying both on the page for the Operacion as well as on the unit's own page.

HOWEVER - this may be an issue with the data, I'm seeing some memberships uncessarily duplicated (rows with the same membership and dates repeated) - which the importer actually did not duplicate.

**Comment by jeancochrane** [comment]
Thanks for taking a look @tonysecurityforcemonitor! I'll dig into `2 Batallón de Infantería` and see if I can figure out what's up. If you have any more links on hand for records that are displaying duplicate memberships, send them my way and I can look at them too.

**Comment by tlongers** [comment]
> one of it's memberships from 3 June 2008 to 15 January 2009 is missing

Perhaps Jean fixed it between Tony's comments and now, but this memberships shows correctly in the corresponding "Memberships" section in the org record for 2 Bat:

```~en/organization/detail/24/#parent-units```
(which links to memberships :) )

**Comment by tlongers** [comment]
@jeancochrane I think we can close this until you're still sensing gremlins in the importer on this matter.

**Comment by jeancochrane** [comment]
@tlongers Fantastic! Feels good to close this one.
