### ISSUE TITLE
Are source being linked to the correct values?

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#241]
@jeancochrane sorry another data modelling question :(

Source 1
Person Name: "Tom"

Source 2
Person Other Names: "Vexorg the Destroyer of Cats and Devourer of Chickens"

Source 2 should not be linked to Person Name, but only to Person Other Names. Is this how it currently behaves?

**Comment by jeancochrane** [comment]
Great question! In this case both `Person Name` and `Person Other Names` will be tied to `Source 2`. This made sense to me, since I figured that identifying `Tom` is also called `Vexorg the Destroyer of Cats` implies that the name `Tom` must have been indicated in the source, too, or we wouldn't know who we were talking about. For `Person Membership`, in contrast, we only add the new source if it's a membership that we haven't seen before (so the autofilled units won't get linked to the new source).

If this isn't right, we can change it around so that only new attributes get linked to `source 2`. For me, that raises the question: how do we indicate that we _want_ to link `source 2` to `Person Name`, in the case that this new source is corroborating information we already know?

Two ways we could approach this, off the top of my head:

1. Method approach that requires little change: staff is expected to remove any autofilled values that are not present in the new source. We automatically link `source 2` to the `Person Name`, since `Person Name` is the primary key that references our entity (or not, if I'm wrong about that; we could also provide a checkbox saying "This value appears in the new source" when autofill is triggered).

2. Interface change: autofill-enabled data entry pages (currently units + personnel) should show checkboxes for all inputs saying "This value appears in the new source" when autofill is triggered. Checking/unchecking those boxes determines what the new source gets linked to.

**Comment by tlongers** [comment]
```Person Name``` and ```Person Other Names``` is an oddity, because the decision about what to include in each field is a analyst judgement. Where a number of sources contain data on a person who is clearly the same person but with different names, the analyst decides which one will be the canonical version. So in this case, we

**Comment by jeancochrane** [comment]
@tlongers that makes a lot of sense to me! Thanks for the detailed explanation.

Sounds like what we want to do is:

1. Update the data entry wizard so we only link sources to new information about personnel/units (with the `Name` being an exception, since (for now) they act as primary keys)
2. Design the edit pages for entities such that each value is linked to flags for keep/update/remove

I also see this as implying a slightly altered (or perhaps just more specific?) data entry workflow, where staff know to use the data entry wizard for adding values to attributes, but not for altering/deleting existing values. We could reinforce this in the UI by adding a link to the data entry pages, along the lines of "Edit/remove wrong information," that pops open a new tab to a pre-populated version of the Edit page with 1) the person/unit the staff member has selected and 2) the source that they've just created.

Is this aligned with what you're thinking?

**Comment by tlongers** [comment]
Issue is expressed in terms of first cut at data capture system: all sources were linked to the index, which was the value in `org:name`, which caused sources that weren't specifically referencing `org:name` to appear in the source widget. @evz is this logic still in place now?

**Comment by tlongers** [comment]
Long resolved modelling issue.
