### ISSUE TITLE
Wire up column sorting in search result tables

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#274]
Straggler issue from #132. Ideally, all tables should be sortable but search results definitely.

**Comment by jeancochrane** [comment]
A first pass at column sorting is in as of https://github.com/security-force-monitor/sfm-cms/commit/ebe199a55bc82c37f8d8554d7d30748e2a49c421.

One interesting issue that came up while implementing this: Solr doesn't support sorting results based on multivalued attributes (e.g. aliases, classifications) since there's no obvious way to sort them. Do we want to write some logic to allow people to sort on them anyway, like picking the term with the lowest-valued start letter and counting that? Do you think people will have an expectation/desire to sort columns like aliases, classifications, and parent units to begin with, or should we let those columns be static?

**Comment by jeancochrane** [comment]
Quick thought while taking a second look: an obvious way to filter multivalued fields might be "has values" vs. "doesn't have values," e.g. many units are missing aliases/parents/classifications and I could see a user intuitively wanting to sort against those.

**Comment by tlongers** [comment]
Your 'has value"/"is empty" suggestion is good, so please go ahead.

**Comment by tlongers** [comment]
I may have misunderstood this commit - should we be seeing a sort buttons on multivalued columns as a result of it?

**Comment by jeancochrane** [comment]
Looks like the deployment didn't go through because I was pushing too many changes all at once. I'll close this once I've confirmed that it's up.

**Comment by jeancochrane** [comment]
Deployed, so you should see the sort buttons on all columns now.
