### ISSUE TITLE
Whitespace in search terms causes 500 server error

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#284]
Whitespace in search terms causes server error e.g "Juan "

**Comment by jeancochrane** [comment]
Great catch! Fixed this in https://github.com/security-force-monitor/sfm-cms/commit/34fa5ebe4636c7953eeb462c1b09e36a1d306b5d so that we strip whitespace when handling queries.

Would it be more helpful for me to turn on Debug mode on the staging site while we're in this phase of intense development/testing, so you can see the traceback when errors arise? We're logging them all to Sentry so it's easy for me to debug, but I can imagine that unexplained 500 errors might be frustrating on your end.

**Comment by tlongers** [comment]
Thanks. No need to stick debug mode on, so long as we know you've got the relevant debug info that's fine.

**Comment by jeancochrane** [comment]
All right, sounds good. Closing this for now then.
