### ISSUE TITLE
Adjust command chart to work with fuzzy dates

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#285]
Currently, entities that have fuzzy dates are messing with the command chart, since we do some date algebra in SQL to figure out command overlap.

[Sentry issue](https://sentry.io/datamade/security-force-monitor-staging/issues/358266252/) and traceback:

```
DataError: date/time field value out of range: "2010-01-00"
LINE 52:               THEN ('2010-01-00'::date BETWEEN start_date::d...
                             ^
HINT:  Perhaps you need a different "datestyle" setting.
```

**Comment by tlongers** [comment]
Yeah, this problem is visible in the unit parent chart. In this case, first citation dates are `YYYY-MM-DD` but last citation dates are `YYYY` only:

~en/organization/detail/64/#parent-units

![sfm_dashboard](https://user-images.githubusercontent.com/2115933/31164887-d15f6042-a8e0-11e7-8270-5c3ea08ef042.png)
