### ISSUE TITLE
Add translation tags to new terms included facets

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#286]
![sfm_dashboard](https://user-images.githubusercontent.com/2115933/31167812-39d27ce0-a8eb-11e7-9fa2-f80d601e92df.png)

**Comment by jeancochrane** [comment]
Also addressed in #227. Translating facet titles is slightly harder, since we pass them in as template variables, and it'll require a little bit of cleverness.

**Comment by jeancochrane** [comment]
This was way easier than I thought, and wound up taking me 5 minutes. Love that feeling. Done in https://github.com/security-force-monitor/sfm-cms/commit/9c5083438f1884e02565fa2ad768948d7648fb65. Since almost all of these words have been translated elsewhere you should see them as soon as the site has deployed in the next ~15 mins.

**Comment by tlongers** [comment]
Uh oh, you're going to loath me now :) ... `Place` and `Parents` in the `unit` filterset are not yet translating:

![sfm_dashboard](https://user-images.githubusercontent.com/2115933/31372819-7d0889de-ad8f-11e7-9340-7389607f4f4e.png)

**Comment by jeancochrane** [comment]
No problem @tlongers, this was a good catch! I hadn't compiled translations in a minute and some were missing. Fixed this on the server.
