### ISSUE TITLE
Creation of unique entity ID numbers

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#288]
@jeancochrane When and how are entity unique ID numbers created? I can't find the function.

**Comment by jeancochrane** [comment]
`uuid` is an automatic field on all of our entity models, e.g. the `Person` model below:

https://github.com/security-force-monitor/sfm-cms/blob/master/person/models.py#L17-L21

While all other attributes of a `Person` have to be set in the `__init__` method (or in the `update`/`create` equivalents), UUIDs get assigned automatically when a new instance of the model is created, like a primary key field.

Does that answer your question?

**Comment by tlongers** [comment]
Thanks, that's answer my question but spawns another related set:
- Do uuids persist across different runs of the importer? (this is prob a dumb question)
- Are record urls permalinks?

**Comment by jeancochrane** [comment]
Ah, some interesting questions here. Not dumb at all!

1. UUIDs do not persist across different runs of the importer, but integer IDs generally _do_, since we iterate over the Google Sheet in the same way each time and increment the IDs in a predictable fashion. (Two exceptions being a case where we change the way we count unique entities, as we did with memberships recently, or where someone changes the order of rows in the spreadsheet.) This is not guaranteed, but rather an interesting byproduct of the way the importer works.

2. Related to 1, record URLs are permalinks insofar as integer primary keys are tied to the same entity across different runs of the importer. So if we wind up changing the way that we count unique entities, or if we move the order of entities in the spreadsheet, integer primary keys could potentially change as well.

Keep in mind that both of these cases only hold when "running the importer" means dropping the database and doing a fresh run. Running the importer against existing data _should_ maintain primary keys/permalinks and only perform updates on new information (except if e.g. someone has edited a unit name in the sheet, in which case we'll think that it's a new unit and mint a new ID for it), with the caveat that I haven't really thoroughly tested that yet. If we anticipate running more imports after the site is public, we might want to verify that this is the case.

**Comment by tlongers** [comment]
Resolved in data model overhaul  -we now mint UUIDs for every entity as a perma-attribute rather than leave this to the importer.
