### ISSUE TITLE
Page content translation process

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#300]
I'm not sure of the status of this [PR on pages](https://github.com/security-force-monitor/sfm-cms/pull/129) and whether there's time to complete it under this Chunk. So, what's the simplest and most pragmatic process for getting static content in, and rendering it translatable?

**Comment by jeancochrane** [comment]
For the sake of speed, I think we should push #129 back to the next chunk. Sending me page content in a Google Doc is a perfectly fine and fast way to get content in. Ideally I'd have that sometime tomorrow, so that I can put it up and let you guys translate it and double-check it before the weekend. You'll have to translate it through Rosetta, but if Michel starts translation now off of the Google Doc it should be a simple matter of copy/pasting. Does that help @tlongers?

**Comment by tlongers** [comment]
Pushing #129 back is fine. We'll provide content in gdocs and use Rosetta for it.
