### ISSUE TITLE
Missing date values from command charts

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#322]
Seems the end dates for parent relationships  - where available -  are no longer displayed at the bottom of the chart:
~en/organization/detail/380/

<img width="675" alt="org_record_anatomy_parents" src="https://user-images.githubusercontent.com/2115933/31770342-578e35d6-b4cf-11e7-887b-79739d3f9325.png">

(Update: added in link)

**Comment by tlongers** [comment]
May be a data issue - it's displaying in others: `~en/organization/detail/225/`

**Comment by jeancochrane** [comment]
Great catch! We weren't handling missing data properly, so this wasn't always working. I also noticed that when the "No known end date" string showed up, we weren't translating it properly. Both of those issues should be fixed in https://github.com/security-force-monitor/sfm-cms/commit/4252f5150771b230d93a04c51ffe0d388ebe241f.
