### ISSUE TITLE
Repeated identical entries in person superiors section

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#336]
Uh oh...

Trouble at `~en/person/detail/23/`:

![whowasincommand](https://user-images.githubusercontent.com/2115933/32053298-d0a8df92-ba52-11e7-8f40-8aa75becb971.png)

Also, the link to `1 Brigade` is incorrect - it links to `~/organization/detail/965/` which is `Special Task Force`.

**Comment by jeancochrane** [comment]
Very strange... have you noticed anything else like this in any other views?

**Comment by tlongers** [comment]
Fishing around a bit it, it seems all personnel linked to `1 Brigade Garrison` have the same problem:

`~/organization/detail/966/#command-personnel`

So:
* O. A. Dada
* Adebowale Ajagbe
* Lawal Ahmed

**Comment by tonysecurityforcemonitor** [comment]
strange, I'm not seeing it...

I've done a review of a lot of units and haven't seen this replicated elsewhere...

**Comment by jeancochrane** [comment]
I wonder if the linking problem is a caching issue. I ran the import
without doing a new deployment, which is when we usually clear the backend
cache. At lunch now, but I’ll look into it this afternoon.

**Comment by jeancochrane** [comment]
Cache seems fine. I suspect [`get_commanders`](https://github.com/security-force-monitor/sfm-cms/blob/master/person/views.py#L118) isn't doing what I think it's doing.

**Comment by jeancochrane** [comment]
Turns out there were a couple of small bugs in the generation and display of the superiors table that got surfaced here:

- We weren't filtering out duplicates (i.e. same person, post, start/end date) when we queried for superior commanders
- Some wrong logic meant that we weren't displaying overlap start/end dates in the appropriate cases
- Rather than link out to the parent unit, we were linking out to the parent of the parent unit

All of these bugs were fixed in https://github.com/security-force-monitor/sfm-cms/commit/65d96ad677829e5743fedb4b901fa8a9f1815726.
