### ISSUE TITLE
Delete function thoughts

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#36]
I know you've not got to that yet but had a few questions. 
- If you delete a specific source, do you also delete all datapoints derived from it? 
- Where a datapoint has multiple sources, which we expect will be common, how will  the deletion of source work?

**Comment by tlongers** [comment]
@tonysecurityforcemonitor thoughts?

**Comment by tonysecurityforcemonitor** [comment]
@evz @tlongers - 

> If you delete a specific source, do you also delete all datapoints derived from it?

Usually when I've deleted a source from an entry in the past its been because the source should not have been attached to that specific field - ie source for name and rank only contained information on a person's name, not rank.

> Where a datapoint has multiple sources, which we expect will be common, how will the deletion of source work?

I think we would need to be able to see what entries the source in question was attached to before making a decision about deleting. That would be helpful in deciding to delete the source from every entry its tied to - or - alternatively discovering a random entry that a source is tied to that should also be deleted (ie from example above - we know we want to delete source from Rank entry, but also see it somehow got attached to a Site entry for an Organization which should also be deleted).

**Comment by tlongers** [comment]
We've moved on a bit from this. See [the wiki page on data integrity](https://github.com/security-force-monitor/sfm-cms/wiki/Note:-Data-integrity-systems-for-WhoWasInCommand.com). Successor to this is #420 really. Closing.
