### ISSUE TITLE
Add access points for sources

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#379]
Wireframe for reference https://app.moqups.com/tom@securityforcemonitor.org/4YZ80oJfVK/view/page/a4d5bfb7b

@tlongers If I kinda missed this earlier. It shouldn't take super long to add if I am understanding the intent correctly: A source can have many Access Points some of which could be on the internet and some of which can be books, etc?

**Comment by evz** [comment]
Couple more questions about access points & sources:

1. Does the "Description of changes" field in the wireframe refer to the source as a whole or just to a particular access point?
2. I notice there is a "Choose subscription service" dropdown in the main source page. Is this a list of things that you already know about or are you going to want to add to this on the fly? Is this a required field?
3. Also, just to cover my bases, the "private source" checkbox means that the source is not publicly accessible? I'm supposing the main upshot of that is that we won't be able to place a link to the source on the public facing pages?

**Comment by tlongers** [comment]
Good questions, thanks. It's fairly fiddly... 

> Does the "Description of changes" field in the wireframe refer to the source as a whole or just to a particular access point?

Source as a whole. I imagined being able to see in the sources history when new access points were created.

> I notice there is a "Choose subscription service" dropdown in the main source page. Is this a list of things that you already know about or are you going to want to add to this on the fly? Is this a required field?

"Private" means "not generally accessible online", rather than "confidential" or "secret". This was designed to cover situations where we used a source that a guest user of the site would not be able to access directly online, despite our efforts. These cases include:

- Print publications with no online versions
- Paywalled  content accessed through some university or corporate network (hence no useful public URL)

In those cases, we still need to do the following:
- reference it as a source: so we store and publish the basic metadata (title, publication date, publisher) and perhaps an access point too (page)
- keep an exact record of where we got it from at the time we used it: if it's from a subscription service, we may be able to provide an exact URL for it (e.g. link to an AllAfrica.com stub page, or a WorldCat or LOC reference URL for a print publication.
- in the event we no URL for tell the guest that the source is subscription only, and tell them which service we got it from from. 

> Also, just to cover my bases, the "private source" checkbox means that the source is not publicly accessible? I'm supposing the main upshot of that is that we won't be able to place a link to the source on the public facing pages?

"Private" should really only be checked where there is no conceivable public URL we can provide. It may be that we have a URL that works for us (e.g. to a direct resource on Columbia's subscriptions). Checking "Private" would hide the URL publicly, but keep it visible so we can use it. Selecting a value from "Accessed via" gives some indication to the guest about why the URL is hidden. 

There are situations were we can provide a URL, but the online content is truncated (paywall). We will still make such URLs publicly available, but also select a value from "Accessed via" to flag that there may be issues accessing it.

Explaining this logic is helpful - thanks for asking. Can you see a clearer way to achieve these ends, as it does seem quite fiddly.

> Does the version table below the Access Points form only apply to the access points or should we make it apply to both the source it's related access points?

Versioning should provide a unified view of the  source along with its access points.

> In the source picker widget, are we just concerned with linking a source to a given attribute or should we also be picking an access point as well?

Access point. Different data points will be evidenced by different access points. 

For example,  the source "Big Report" has two access points:
- page 30 evidences a site
- page 49 evidences a person in the role of commander

Another example, the source "Police Web Page" has three access points:
- an archive snapshot from 2006 puts Person X  in a command position of Org A
- an archive snapshot from 2010 puts Person X in a command position of Org B
- an archive snapshot from 2018 puts Person X in a command position of Org C

**Comment by evz** [comment]
Thanks for the detail here. I'm going to be working on this today so I'll let you know if any other questions crop up.
