### ISSUE TITLE
Sources: versions created even if if no changes made to record

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#402]
1. Visit a source
2. Click edit
3. Click save
4. Click edit and you can see a new version of the record has been created, although no content has changed

Is this necessary?

**Comment by tlongers** [comment]
Although in the current round of dev, we are not pursuing the version control, this may flag something going on with basic CRUD that we do want to fix.

**Comment by jeancochrane** [comment]
After digging into this a little bit I feel confident that this is unrelated to the basic CRUD in the system. Saving Sources looks good. However, I'm not sure if there's an easy way to prevent this from happening, as it's an intended side effect of our versioning library, `django-reversion`.

Currently, we have `django-reversion` configured to automatically create new versions on `POST` requests to all create or edit views, including Sources. (EvZ left some background on this in his [development docs](https://github.com/security-force-monitor/sfm-cms/blob/master/DEVELOPMENT.md#where-the-magic-is-and-a-little-bit-about-how-it-works), under the `Versions` heading.) `django-reversions` exposes a configuration option, [`ignore_duplicates`](https://django-reversion.readthedocs.io/en/stable/api.html#registration-api), that's intended to allow you to stop a revision from being created if nothing changed on the object. However, since Sources have a `date_updated` field that always updates to the current time, it will effectively _always_ appear to have "changed" on any `POST` request, whether the user changed any fields or not.

A couple options for how we can proceed here:

1. Remove the `date_updated` attribute from Sources and see if we can use `ignore_duplicates` to prevent these versions from being created. We could probably retrieve the equivalent of the `date_updated` attribute dynamically by just querying for the most recent Version and getting its `date_created` attribute.
2. Make use of the methods on [`sfm_pc.utils.VersionsMixin`](https://github.com/security-force-monitor/sfm-cms/blob/a83ae5a5e3e409e28333104ec3757be42588eb02/sfm_pc/utils.py#L322) (which `Source` inherits from) to filter out these duplicate versions on the frontend. This would mean that extraneous versions would still get saved, they just wouldn't be exposed to the end user.
3. Do nothing, and accept that we'll have some extraneous versions for Sources if users interact with the form this way.

Whatever we decide, we should also consider whether this is a basic requirement of the data entry system or whether this is actually a versioning issue. To me it seems like the latter.

**Comment by tonysecurityforcemonitor** [comment]
Thanks @jeancochrane - for now let's do option 3, though in the future it seems like option 2 may be the way to go. I agree that this does seem like a versioning issue so it seems to make sense to not open that particular can of worms right now.

**Comment by tlongers** [comment]
Thanks @jeancochrane for the excellent briefing on this issue. I'm reassured that this doesn't interfere with the basic CRUD, so we'll return to this issue down the line when we give more attention to a reviewing system.

**Comment by tlongers** [comment]
Deprecated feature; closing.
