### ISSUE TITLE
Incident type is not displaying correctly in read-only view

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#428]
On staging.

`~/en/violation/view/f7da0e68-6bf3-46be-93d0-266091cfba4e/`

Values recorded under Incident type are not displaying. Rather than three black boxes, there should be three values here: `beating`, `illegal detention`, and `torture`.

![image](https://user-images.githubusercontent.com/2115933/45746411-21059700-bbfb-11e8-8727-c4e52e5aedb5.png)

**Comment by evz** [comment]
This is actually related to a bug I had in a database migration I wrote. Once I deploy these changes to the staging server. I'll need to do a bit of surgery to get those to show up properly again. This should not be an issue once we deploy everything to production since that migration has not been run over there (and I have a few backups of that database for good measure anyways).
