### ISSUE TITLE
Multi-value fields like person:other_names and org:other_names must always have at least one source

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#435]
It should not be possible for a multi-value field with a single value in it to exist without a source. I think that this is currently the case, though I can't demonstrate it because changes are not committing to the database

**Comment by evz** [comment]
This was actually due to the caching problem from #434. Since the edit pages were being cached but the sources being loaded by the source picker were not, the aliases were not actually associated with the person anymore which meant that when we tried to get the sources, there were of course no sources. So, the database was consistent, it was just the UI that wasn't. I'll let you verify this and then close the issue if it seems like that is the case.

**Comment by tlongers** [comment]
#434 is still live. Will look at this when that's nailed.

**Comment by tlongers** [comment]
Re-opening because the fix for #434 isn't enabling us to add sources to any data point, so we can't test this issue.

**Comment by tlongers** [comment]
Refers to a deprecated feature; closing.
