### ISSUE TITLE
Add ability to create organizational hierarchy

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#45]
Add a way to enter parent organizations to the page for entering Organizations. This suggests a bit of UI complexity given that it seems pretty likely that parent organizations will be entered at the same time as their children (and one could imagine that several layers of hierarchical information could be contained within a single source). @tonysecurityforcemonitor Does it make sense to just instruct users to start with the "largest" or "highest" (not sure what the best term is there) and then, as they add organizations, allow them to create relationships with Organizations that are already entered into the form? So, for instance, you would enter NYPD, then when you enter Patrol Borough Manhattan South, you could add NYPD as the parent and then when you add the 9th Precinct, you could add the Patrol Borough Manhattan South as the parent.

**Comment by tonysecurityforcemonitor** [comment]
@evz I've been chewing this over a bit --- because there would be the same UI complexity with the Other Affiliation/International Affiliation fields.

Would we save ourselves a lot of trouble if entering data on relationships between organizations was done on another "screen"?

I've taken a look at the sourcing and the percentage of sources that have parent/other affiliation/peacekeeping information is very, very low - meaning that a user could simply "skip" that screen as it will often be blank.

I do think having all those relationships between organizations entered on one screen makes sense as they all roughly have the same type of fields (the only "extra" fields are for parent relationships with the classification of the type of relationship and if it is being assumed to the current date).
