### ISSUE TITLE
Quick question on incident locations

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-cms#488]
So, I'm wiring up the new location stuff to the edit / create views and looked back on the moqup for the incident location view (https://app.moqups.com/tom@securityforcemonitor.org/4YZ80oJfVK/view/page/ae421e3ed) and I just have a couple questions:

1. Are we thinking there should be more than one location per incident? The way the data model is laid out, it assumes one location per incident. This, remarkably, should not actually be difficult to change, I just need to know. 
2. Should each location be separately sourced?
3. It looks like a lot of the fields that are in that edit view are already present in the location model. Is there any reason to also have incident specific versions of those fields?

**Comment by tlongers** [comment]
Good questions, thanks @evz. 

I'll work through a situation where we'd have to add a location to an incident and get us to answers that  way. We have the following fields to populate:

Field|Usage|
-|-
`Location`|Narrative description taken from the source|
`Site: Exact Location - Longitude or OSM Node Name`|Conditional field - exact node, or coordinates
`Site: Exact Location - Latitude or OSM Node ID`|Conditional field - exact node, or coordinates
`City or smallest administrative unit GeoName`|Nearest settlement node name
`City or smallest administrative unit GeonameID`|Nearest settle node OSM node ID
`ADMIN1 Geoname	`|Name of Top admin level containing location
`ADMIN1 GeonameID`|OSM ID or top admin level containing location
`division_id`| Country

Let's say our location is `Giwa Barracks`. This is actually a `way` in OSM ([here](https://www.openstreetmap.org/way/196204935)) so we'd pick the OSM `node` closest to its centre, in this case [196204935](https://www.openstreetmap.org/node/196204935). 

We'd then go on to find the nearest settlement ([Maiduguri, OSM node ID 27565111](https://www.openstreetmap.org/node/27565111)).

From there the corresponding ADMIN1, which is Borno State ([OSM relation ID 3721167](https://www.openstreetmap.org/relation/3721167)). 

Although on the map, we just display the point, we collect the additional location information in order to enable a wider analysis. For example, being able to filter down to "all incidents in Borno State". 

We'd assign the `division_id` by choosing the country list. 

The issue here is what we can expect the location app to do auto-magically.  If we enter a node ID for the exact location, I would expect the location app could grab the ADMIN1, but not assign the nearest settlement, which is more subjective.

So, to your questions.

> Are we thinking there should be more than one location per incident? The way the data model is laid out, it assumes one location per incident. This, remarkably, should not actually be difficult to change, I just need to know.

AND...

> It looks like a lot of the fields that are in that edit view are already present in the location model. Is there any reason to also have incident specific versions of those fields?

In the case where we have really detailed information we will need to assign an exact location node, a nearest settlement node, and an ADMIN1. The display logic should be in that order: no exact location, then show the nearest settlement; no nearest settlement, then show the ADMIN1. 

At its simplest, the system need just have one location field: and we choose what to enter in there, and what level of detail it represents. At its most complex, we enter all three options, and choose which to display on the read-view of the record.

> Should each location be separately sourced?

No. An individual incident  is always drawn from a single source. We don't want to change this just yet.

That... helpful? @tonysecurityforcemonitor does this read right to you?

**Comment by tonysecurityforcemonitor** [comment]
I think that lays it all out nicely @tlongers ...

The only thing I'll add (or I guess emphasize) is that I was expecting locations in terms of Incidents to be handled the same as they would be in terms of Organizations. As Tom laid out:

> In the case where we have really detailed information we will need to assign an exact location node, a nearest settlement node, and an ADMIN1. The display logic should be in that order: no exact location, then show the nearest settlement; no nearest settlement, then show the ADMIN1.
> 
> At its simplest, the system need just have one location field: and we choose what to enter in there, and what level of detail it represents. At its most complex, we enter all three options, and choose which to display on the read-view of the record.

I'd expect a similar dynamic when it comes to locations for organizations... right?

**Comment by tlongers** [comment]
That is a good question: does the location app snarf down ADMIN1?

**Comment by evz** [comment]
As we discussed on the call, I'm just going to make it so you guys can separately add the exact location, admin1 and nearest settlement for incidents.

**Comment by tlongers** [comment]
@evz I see on the staging server that the Place facet is basically all `None` now? Have the current `ADMIN1` values been loaded?

**Comment by evz** [comment]
Hmm ... let me make sure that's actually getting put into the index as expected.

**Comment by evz** [comment]
So, this led down a bit of a location rabbit hole which had a couple of positive otucomes:

* When saving a location, it will automagically get associated with it's adminlevel1 and adminlevel2 or associated with anything that we already know about for which it is the adminlevel1 or adminlevel2
* The place facet now has places in it.

We still have over 7000 organizations for which we have no admin level 1 for, however (which is what we are using to populate that place facet). Is this expected?

**Comment by tlongers** [comment]
Stale! Locations have changed quite a lot since we reported this.
