### ISSUE TITLE
[Staging] Deleting a location renders any organization record linked to it unviewable

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#508]
1. Add a location (choose a node)
2. Add it as a site to an organization that had no previous site
3. Delete the location you just added
4. Attempt to view the record for that organization again -  server error!  The record is still in the search index though.

**Comment by tlongers** [comment]
Here's an example of a record that has this problem: `~en/organization/view/59b8e3b6-0202-493d-b10d-04892c97adea/`

**Comment by jeancochrane** [comment]
I suspect this is happening because the `LocationDelete` class doesn't account for entities that may be linked to it:

https://github.com/security-force-monitor/sfm-cms/blob/c264237ec5d1b1a4c4a6e5fdf77a26a088637eb0/location/views.py#L98-L101

Related to #420. We need to either 1) prevent the user from deleting Locations until they've removed all entities that have linked to it (which would require updating the Location detail view to expose this information) or 2) implement some kind of cascading behavior that would automatically remove any relationships between Locations and other top-level entities. Path 1) seems like the simplest path forward for now, but path 2) seems like a more useful feature in the long-run.

**Comment by tlongers** [comment]
Refers to deprecated feature; closing.
