### ISSUE TITLE
[PR544] Clearing a posting's rank field is not possible

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#553]
1. Go to a unit with personnel attached to it, and edit it.
2. Go to `personnel` and pick a posting.
3. Choose a value for `rank` and associate a source, then click save.
4. Edit the posting again and clear the value for rank (select `------`), clear the source and again save.
5. The value for rank will not be updated.

Expected behaviour is that clearing both the value and corresponding sources of a non mandatory field will enable an empty value to be saved.

**Comment by tlongers** [comment]
Reproducing this causes a server error mid way through.

**Comment by derekeder** [comment]
I was unable to reproduce the error @tlongers is referring to in https://github.com/security-force-monitor/sfm-cms/issues/553#issuecomment-513261735

This issue may have been resolved in https://github.com/security-force-monitor/sfm-cms/pull/592

I did encounter a different error when saving a blank value but not clearing the source, which I have documented in https://github.com/security-force-monitor/sfm-cms/issues/598

Please confirm if this bug is still happening.

**Comment by tlongers** [comment]
Yeah, so if you clear the sources rank will be updated. If you don't clear the sources (as in #598) a server error occurs.

**Comment by jeancochrane** [comment]
Sounds good, superceding this by #598 then.
