### ISSUE TITLE
URLS in popovers can't be accessed

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#564]
1. Visit any page on WWIC ([for example](https://whowasincommand.com/en/organization/view/a9f3802f-75d6-4ee1-b2f9-b438d1e16f1e/)).
2. Activate any popover for sources until you see one with a hyperlinked URL in it.
3. Hovering over the hyperlink shows it is valid and points to a destination URL.
4. Clicking the link closes the popover, rather than opens a new tab with the destination URL.

Any easy fix for this @jeancochrane ?

**Comment by jeancochrane** [comment]
Good catch -- I think this is probably being caused by the fact that we use a click event anywhere on the page to close the popover (so that users don't have to click the tiny X to close it). I haven't looked at the code in a while, but we might be able to fix this pretty easily by adjusting that event to exclude clicks that happen on the body of the popover itself.

**Comment by tlongers** [comment]
Thanks. We'll queue a fix for the next chunk.

**Comment by tlongers** [comment]
Is this pushed to production, or just in special instances?

**Comment by jeancochrane** [comment]
We merged #665 on March 2nd and our [latest release](https://github.com/security-force-monitor/sfm-cms/releases/tag/v1.4.3) was on September 3rd so this should be active in production. Are you noticing issues with the fix?

**Comment by tlongers** [comment]
Nope it's all good. I was wondering why the issue was still open. Do you want to do the honours?

**Comment by jeancochrane** [comment]
This was one of a couple of issues in the ["QA" column of our last project](https://github.com/security-force-monitor/sfm-cms/projects/5) that were fixed on staging but awaiting approval from your end before getting deployed. (I also dropped the ball and forgot to follow up on them after our last scope!) Since all of the QA issues have been deployed to production at this point, how do you feel about me closing them all out, including this one?

**Comment by tlongers** [comment]
A very delayed thanks @jeancochrane
