### ISSUE TITLE
Server error template doens't acknowledge if user is logged in or not

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#582]
If a user is logged in, and a server error is displayed, the navigation links change to those displayed for guests. Also, on the same screen, the user language choice is not respected. Here, the dropdown defaults to Spanish, but the language choice is English.

![image](https://user-images.githubusercontent.com/2115933/61545916-6e7faa00-aa40-11e9-9695-4f5c7e53c8e1.png)

(For testing, this record throws an error: `en/organization/view/59b8e3b6-0202-493d-b10d-04892c97adea/`)

**Comment by derekeder** [comment]
I'm unable to reproduce this issue on https://whowasincommand.com

While logged in and navigating to this page: https://whowasincommand.com/en/organization/view/59b8e3b6-0202-493d-b10d-04892c97adea/

I am able to see the expected Logout link and language preference:

<img width="1278" alt="Screen Shot 2019-08-07 at 3 33 04 PM" src="https://user-images.githubusercontent.com/919583/62656001-e0089500-b928-11e9-9a02-ced1c2111ce3.png">

@tlongers can you confirm this is still an issue you are encountering?

**Comment by tlongers** [comment]
You're right that the Issue doesn't occur on the production instance, but it still occurs on staging at:

`~/en/organization/view/59b8e3b6-0202-493d-b10d-04892c97adea/`

**Comment by jeancochrane** [comment]
I think the confusion here is due to the fact that in Django, 404 errors will return a view with the standard user context, but 500 errors won't. This unit doesn't exist in the production database, so we get a 404 error with the proper user context; the unit exists on staging and has corrupted data (a Location was removed without removing this unit's corresponding Emplacement), so we get a 500 error without proper user context.

Note that the lack of user context on 500 views is by design: Django doesn't return any context in 500 error responses by default because it believes that adding context increases the chance of causing additional bugs in the rendering of the 500 response view ([source](https://docs.djangoproject.com/en/2.2/ref/views/#the-500-server-error-view)). That being said, people [often customize the 500 response view to add user context](https://stackoverflow.com/q/26043211), and we could do that here as well.

**Comment by tlongers** [comment]
How do we corrupt a record on staging so we can test this?

**Comment by jeancochrane** [comment]
@tlongers The link you posted in the body of the issue should still work: https://back.securityforcemonitor.org/en/organization/view/59b8e3b6-0202-493d-b10d-04892c97adea/

**Comment by tlongers** [comment]
Cool, that's fixed then.
