### ISSUE TITLE
Downloads—Updating basic functionality

### ISSUE THREAD

**Issue by jmithani** [security-force-monitor/sfm-cms#602]
Splitting off from #516 
- [x] Put the country or ISO shortcode in the download file name
- [x] `start_date_of_organization` should be `Y` or `N`
- [x] Parentage: `real_start_date` should be Y/N
- [x] Sites: `real_start_date` Y/N
- [x] Areas: `real_start_date` Y/N
- [x] Sources: add page numbers to access points
- [ ] Add `org:notes`
- [x] Memberships: add `member_name` country id 
- [x] Sites: country ID of site is missing
- [x] Areas: country ID of site is missing
- [ ] Personnel: notes field missing
- [x] Personnel: person country is missing 
- [ ] ~~Sources: add UUID~~

**Comment by jmithani** [comment]
@tlongers it doesn't look like the `organization` model has a `notes` field. What are you referring to here?

**Comment by jmithani** [comment]
cc @tonysecurityforcemonitor (for the above comment!)

**Comment by jmithani** [comment]
A few notes to myself:
- Confirm whether country ID refers to `division_id` or the ISO code a lá [this entry](https://help.securityforcemonitor.org/v/en/data-model/events#event_country)
- Test whether Personnel:Notes is producing the correct data
- Seek clarity on published UUIDs (probably from @jeancochrane)

**Comment by jmithani** [comment]
Questions and comments for @tlongers @tonysecurityforcemonitor:

- I can't access source `0717c474-c48e-4d9e-a9fc-a3bf09d5203d` for testing. What is the plain name so I can search for it?
- For Personnel:Notes, we have it selected (see https://github.com/security-force-monitor/sfm-cms/blob/master/sfm_pc/sql/personnel.sql#L19). Is there an example you can give of this not working as expected?

Comments:
- We do not store the UUID for publications for sources. Right now it is only saved as a text field. A suggested improvement for the future would be to change this to a ForeignKey so we can capture those IDs.
- Organizations don't have notes according to our models, but [it is listed as an attribute in the Research Guide](https://help.securityforcemonitor.org/v/en/data-model/organizations#organization_notes). We should sync on this and make sure we are collecting the required information.
- I saved `country_iso` as a field equivalent to "country_id." If the two-characters ISO isn't adequate, I can easily change it.

**Comment by tonysecurityforcemonitor** [comment]
@jmithani

> I can't access source 0717c474-c48e-4d9e-a9fc-a3bf09d5203d for testing. What is the plain name so I can search for it?

Strange, I'm not seeing a source with that UUID... what record is it attached to?

> For Personnel:Notes, we have it selected (see https://github.com/security-force-monitor/sfm-cms/blob/master/sfm_pc/sql/personnel.sql#L19). Is there an example you can give of this not working as expected?

A question for @tlongers ; )

> We do not store the UUID for publications for sources. Right now it is only saved as a text field. A suggested improvement for the future would be to change this to a ForeignKey so we can capture those IDs.

Yes it would be good for all sources to have associated UUIDs

> Organizations don't have notes according to our models, but it is listed as an attribute in the Research Guide. We should sync on this and make sure we are collecting the required information.

We've been using this as a free text field, referencing the related sources by their UUIDs. Probably could be implemented better though... It is also rarely used, but useful container for contextual information that is outside of our data model.

**Comment by jmithani** [comment]
@tonysecurityforcemonitor 

> Strange, I'm not seeing a source with that UUID... what record is it attached to?
@tlongers referenced it as an example of a source with multiple pages in #516. I'll wait until he comes back to check in!

>We've been using this as a free text field, referencing the related sources by their UUIDs. Probably could be implemented better though... It is also rarely used, but useful container for contextual information that is outside of our data model.

When editing an organization, which form field are you filling out? I don't see any open text fields.

**Comment by tonysecurityforcemonitor** [comment]
Ok sounds good : )

**Comment by tlongers** [comment]
Thanks for the work here @jmithani. To answer questions from above: 

- source `0717c474-c48e-4d9e-a9fc-a3bf09d5203d ` may have been one I added for testing, so would not exist in your dev environment or current staging servers. 
- Yes, ISO is the two letter shortcode we use for countries. For some reason, we call it a `division_id` in the data :/ We aim to harmonize all our fieldnames across documentation, data entry and download, as it has become a mess - for now though, we focus on getting the download function working well.
- Regarding notes fields: I thought they had been added to the table and imported, but it seems note. We'll consider what to do about this in another issue. 

I've gone through the list and either confirmed the fix, or asked a question. In general, when adding a new download field try to name it so it's clear what it refers to: `country_iso` is expressive, but `person_country_iso` is better. I couldn't test fixes to the `sites` data, because the download wasn't populated below the header. 

I grabbed all the available downloads for Mexico, which I'll use to test these fixes.

```
areas_MX_2019-09-13T11_00_50.075830+00_00.csv
basic_MX_2019-09-13T10_56_04.354124+00_00.csv
memberships_MX_2019-09-13T11_00_47.379643+00_00.csv
parentage_MX_2019-09-13T11_00_44.203097+00_00.csv
personnel_MX_2019-09-13T11_00_57.940759+00_00.csv
sites_MX_2019-09-13T11_00_54.162148+00_00.csv
sources_MX_2019-09-13T11_01_01.931136+00_00.csv
```

- [x] Put the country or ISO shortcode in the download file name

Shortcode is present in the filenames. 

- [x] start_date_of_organization should be Y or N

Sort and count of `start_date_of_organization` confirms this fix.

```
   1 start_date_of_organization
  26 ""
 126 Y
 846 N
```
- [x] Parentage: real_start_date should be Y/N

Sort and count of `start_date_of_organization` confirms this fix.

```
   1 start_date_of_organization
  34 ""
 143 Y
 933 N
```

I also checked the below for anything untoward, and all were fine:
```
 10: open_ended
 15: relationship_realstart
 17: relationship_open_ended
```

- [ ] Sites: real_start_date Y/N

The sites download is empty but for the header row. I'd be expecting >300 rows for the Mexico data, so something has gone wrong here.

- [x] Areas: real_start_date Y/N

Confirmed.

```
   1 start_date_of_organization
  24 ""
 177 Y
2328 N
```

- [x] Sources: add page numbers to access points

Fixed; returns the correct page numbers, whether singular, multiple, ranges, and mixed values.

- [ ] Add org:notes

Hrrm. I can't see this being grabbed by the importer, which I had thought it was. Can you check in the schema to see if there is even an entry for it? I suspect that we talked about adding in this field, and then either forgot or were deterred by the phrase "table changes" :) 

- [ ] Memberships: add member_name country id

I have a few questions before confirming this fix. Here's the field list I get:

```
  1: uuid
  2: name
  3: division_id
  4: country_iso
  5: classifications
  6: other_names
  7: first_cited_date
  8: last_cited_date
  9: start_date_of_organization
 10: open_ended
 11: member_id
 12: member_name
 13: membership_start_date
 14: membership_end_date
 15: membership_real_start
 16: membership_real_end
```
Do the values in  `country_iso` correspond to the organization entities listed in `member_name`? If that's the case, please move the position of `4:country_iso` to between the current columns 12 and 13 and rename it to `member_division_id`

Also, the data formats for the two are different in this download. `division_id` contains values in this format:`ocd-division/country:mx`. The values in `country_iso` are in a simpler format: `mx`, which we would prefer to be used across all downloads where `division_id` is present.

- [ ] Sites: country ID of site is missing

As above,field `country_iso` is added but I'm not sure whether this refers to the ISO value of the site itself, or the organization to which the site is attached. If the value is correct, let's rename the country_iso field to `site_division_id`

- [ ] Areas: country ID of site is missing

I see `country_iso` - is the value drawn from the area, or from the org to which the area if attached? If so, as with the above, let's rename it `area_division_id` and move it between the current columns 12 and 13.

- [ ] Personnel: notes field missing

There is a notes field on the current person record, but this is not populated with data from the notes field in our data. Similar to `org:notes` above, I think we may have not got round to the dev required to update the table and importer to add this. 

- [ ] Personnel: person country is missing

Similarly, confirm that `country_iso` take values from `person:division_id`? Also, the fieldname should be more descriptive `person_division_id` and moved to accompany related data on persons - so between current columns 13 and 14.

- [x] Sources: add UUID

This is fixed. Now we have both the uuid of the source  and the uuid as the access points in the downloads.

**Comment by jmithani** [comment]
@tlongers I'm working my way through this!

First, for the sites I was able to download this file for Mexico locally: https://gist.github.com/jmithani/875541ea55d53436ce90d5cbdce461a5

On the staging site, it looks like none of the sites are generating downloads. I've added this as #641.

I see that we have an area for Person notes but don't have that in the importer. For Organizations, we don't have a notes field nor a section in the importer.

I'm looking into your questions about the country codes and will respond soon. (Have to refresh my work on this PR a little bit...)

**Comment by jmithani** [comment]
> Do the values in  `country_iso` correspond to the organization entities listed in `member_name`? If that's the case, please move the position of `4:country_iso` to between the current columns 12 and 13 and rename it to `member_division_id`

> As above,field `country_iso` is added but I'm not sure whether this refers to the ISO value of the site itself, or the organization to which the site is attached. If the value is correct, let's rename the country_iso field to `site_division_id`

> I see `country_iso` - is the value drawn from the area, or from the org to which the area if attached? If so, as with the above, let's rename it `area_division_id` and move it between the current columns 12 and 13.

In all these cases, the `country_iso` refers to the organization `division_id`. I will plan to go in and add `member_division_id`, `site_division_id`, `area_division_id`, and `person_division_id`.

To confirm: all of these should be the two-character ISO code?

Would you like me to change the `division_id` (column three) to be an two-character ISO code as well?

**Comment by tlongers** [comment]
> In all these cases, the country_iso refers to the organization division_id. I will plan to go in and add member_division_id, site_division_id, area_division_id, and person_division_id.

Where `division_id` is drawing values from the same field as any of the other `country_iso` fields, then just include the `country_iso` with the relevant prefix (e.g. `site_country_iso`). I greatly prefer "country" to "division" as a label for this field type.

> To confirm: all of these should be the two-character ISO code?

Yes. The values in this field are all two-character values taken from `ISO 3166-1 alpha-2 code` list.

> Would you like me to change the division_id (column three) to be an two-character ISO code as well?

Yes. It currently has some additional cruft in it that would be great to remove.

**Comment by jmithani** [comment]
I pushed some new changes:
- Column three (`division_id`) is now a two-digit ISO code
- I moved the `{download}_country_iso` to the logical place in the spreadsheet

Clarification for my last comment:
`division_id` is drawn from the `organization_organizationdivisionid` table. `{download}_country_iso` (and the final `division_id`) is a substring of that. Should for example `person_country_iso` be drawn from the `person_persondivisionid` table? (Note that at least the `area_areadivisionid` table is empty, if that affects your answer.)

**Comment by tlongers** [comment]
There's a good chance I'm wrong here but the naming of `organization_organizationdivsionid` reads more like the value could an attribute of the parent of the organization than the organization itself. Can you check this?

**Comment by jmithani** [comment]
`organization_organizationdivisionid` is the correct table. That format comes from the way `ComplexFieldContainer` renders the values. (It's defined here if you want to see the specifics: https://github.com/security-force-monitor/complex_fields/blob/master/complex_fields/base_models.py#L68-L76.)

After talking to @jeancochrane it looks like a few things need to be reworked to get these downloads functional in the way you need. Right now, the only `division_id` logged in the download is of the related organization. So if you were looking at a download of sites in Mexico, `division_id` would refer to the organization they belong to versus the country the site belongs to.

We're going to now have two country codes in each download: the country code of the organization (`organization_country_iso`) and the country code of the entity in question (e.g. `site_country_iso`) since it's very possible those could differ. For parentage downloads, we'll have `child_country_iso` and `parent_country_iso`.

Does that sound right to you @tlongers?

**Comment by tlongers** [comment]
>We're going to now have two country codes in each download: the country code of the organization (organization_country_iso) and the country code of the entity in question (e.g. site_country_iso) since it's very possible those could differ. For parentage downloads, we'll have child_country_iso and parent_country_iso.

That exactly right @jmithani, thank you. Somewhat tediously, we'll likely rename these labels as we harmonise field names across our different products (see https://github.com/security-force-monitor/sfm-cms/issues/640 for more on this). For now though, please stick with your suggested names.

**Comment by jmithani** [comment]
Great, thank you! I'll work on this today.

**Comment by tlongers** [comment]
Oh downloads! Closing: we've moved past this point a bit now.
