### ISSUE TITLE
Violation Location field gets saved as Description field

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#604]
Bug I noticed while editing Violations: If you edit the Location field on the `edit-locations` form, the Location value will wind up getting saved on the `Violation.description` field.

**Comment by tlongers** [comment]
@jeancochrane would this be the right test for this?

1. Create a new incident.
2. Add text of the field `Description`.
3. Add a location with some different text in the `Location description` field.
4. Save the record.
5. Edit the record, and change the text in the `Location description` field.
6. Save the record.
7. Check whether the text in `Description` is the same as the text just added to `Location description`.

When I ran it, the test fails, and so the bug is fixed on staging.

**Comment by jeancochrane** [comment]
Yup, that sounds right to me @tlongers! Thanks for piecing those testing instructions together.
