### ISSUE TITLE
Add Location not working

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#610]
I don't seem to be able to add a location to an organization.

1) Edit the 1 Mechanized Division: ~/en/organization/view/3f560bc4-c103-46f8-9e14-2058814bee66/
2) In "Locations" click "Add Site"
3) Type in "Kaduna" which exists as a ~/en/location/view/27565091
4) No results displayed so unable to add location

![image](https://user-images.githubusercontent.com/18744855/63617667-0af51900-c5b8-11e9-9e7d-e2b5e4852a41.png)

**Comment by jeancochrane** [comment]
Thanks for flagging this! I'm able to load this Location as expected in dev, so I suspect that something in the staging database is out of whack.

**Comment by jeancochrane** [comment]
Alright, I've got some more info on this mystery. The core problem is that when we edit Emplacements, we restrict the Locations query to Locations where `feature_type=node`:

https://github.com/security-force-monitor/sfm-cms/blob/7dc9fa23c9da8dcdbadd4b4fe1a2de2efabbc4e4/templates/organization/edit-locations.html#L96-L100

Problem is, on the staging server, there are only two Locations with the feature type `node`:

```python
>>> Location.objects.filter(feature_type='node').count()
2
```

However, in my local environment, the count jumps substantially:

```python
>>> Location.objects.filter(feature_type='node').count()
2333
```

In both cases, there are _way_ more Locations with the feature type `point` (which is equivalent to `node`, I believe):

```python
>>> Location.objects.filter(feature_type='point').count()
750676
```

Now, it seems like when we run the `link_locations` management command during app setup, it will automatically coerce all the Locations it creates to the feature type `node` or `relation`:

https://github.com/security-force-monitor/sfm-cms/blob/7dc9fa23c9da8dcdbadd4b4fe1a2de2efabbc4e4/sfm_pc/management/commands/link_locations.py#L108-L111

However, we only run this logic for Locations in admin levels 1 and 2:

https://github.com/security-force-monitor/sfm-cms/blob/7dc9fa23c9da8dcdbadd4b4fe1a2de2efabbc4e4/sfm_pc/management/commands/link_locations.py#L85-L93

This leads to my theory of why there's a discrepancy between staging and dev: on the staging and production servers, we must have an old version of the OSM data, from before this change was implemented. (When Forest and I did the last data import, we didn't touch the locations data, since it takes so long to import.) If this is true, we should be able to fix the discrepancy between staging/production and dev by redoing the OSM imports on the servers.

However, even if this is true, it still doesn't help me understand the core problem here: **what's the difference between `point` and `node`, and why is `point` supported at all if we only ever reference `node` in the application?** Why does the importer only adjust `point` to `node` for admin levels, and not all Locations?

I wish I had a better understanding of what we're trying to do with OSM feature types, but unfortunately there's a lot of history here that I wasn't privy to.

**Comment by tonysecurityforcemonitor** [comment]
Hmmm... I'm not sure about that point and node issue either. Something for @tlongers.

I'm also not sure if this is operating under the logic that Locations=nodes, which isn't correct as Organizations and Incidents can have locations which are Ways or Relations.

**Comment by tonysecurityforcemonitor** [comment]
Similar issue when trying to add a location to an incident...

**Comment by tlongers** [comment]
I noticed this as well (see https://github.com/security-force-monitor/sfm-cms/issues/575) - we have a location type `polygon`. I don't know why either `point` or `polygon` are in use at all. Let me investigate further.

**Comment by tlongers** [comment]
[Today I talked about this issue with @jeancochrane and @tonysecurityforcemonitor over another channel. Here's some additional details that build on the comments above]

As noted, `sites` and `areas of operations` are composed of a range of fields that capture different levels of locational precision. This approach means we can be capture precisely what the source material can evidence. 

The more general locational attributes, like `ADMIN1` also open up valuable analytical angles; they provide simple ways to filter and facet by larger locations ("show me all sites in this county or state"). To recap,  `ADMIN1` values are taken from the highest level level sub-national administrative level [as specified in OSM](https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative#admin_level).

Whilst we specify `ADMIN1` independently, in most cases we are simply picking out this value from OSM (using [Nominatim](https://nominatim.openstreetmap.org/)) rather than independently researching it. If we have a source that says `Gamma Unit` was at `site X`, and we know from Nominatim that the OSM node for `site X` falls within the OSM relation labelled `State of Y` (and admin level 4 relation), we will enter "State of Y" as the value in `ADMIN1`.  The value that appears in `ADMIN1` in WhoWasInCommand is intended to appears in the `Places` facet in the `units` search screen, enabling this kind of handy drill-down (though, because of the problems documented in this issue, it is not currently functioning).

However, we can't directly edit the `ADMIN1` values for `sites` through the data entry system, even though in our spreadsheets we do edit this directly. Although we do not have documentation for this, I _think_ we attempted to introduce an optimization by having location importations processes (whether through the management command `import_osm` or the on-demand mechanism that uses Overpass API)  _automagically_ grab the correct `ADMIN1` value for any other OSM object we introduce. After all, if it's something we would do manually and the outcome is identical, then why not? 

This needs confirming, however.  If this is the case, and `ADMIN1` is being correctly assigned through these processes, then this is a positive and is what we intended to do. If it does not, then we have to consider how to assign the correct `ADMIN1` values in other ways.

**Comment by tlongers** [comment]
Is #647 implemented on staging?

**Comment by jeancochrane** [comment]
@tlongers Partly -- Sites should now be opened up to any feature type, but I ran into a snag with cleaning up the extraneous Locations in the DB. Seems like the staging server doesn't have enough memory to run the query that deletes all the ~million locations. Brainstorming another way around it today.

**Comment by tlongers** [comment]
#647 partially blocks testing here.

**Comment by jeancochrane** [comment]
Locations have been cleaned up, so this should be ready for QA!

**Comment by tlongers** [comment]
Closing. We moved the vaguaries of Location creation and managing the relationship with OSM to a separate system and an improved data model. Most of the issues here are resolved.
