### ISSUE TITLE
Adding extra forward slashes to root url results in inconsistent behaviour

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#625]
Adding increasing numbers of forward slashes at the end of the root url results in some inconsistent behaviour:

1. `~/en/organization/edit/composition/76cd0d81-1c70-4630-bf8b-5876868942ee/4/` is the URL of a valid edit view
2. `~//en/organization/edit/composition/76cd0d81-1c70-4630-bf8b-5876868942ee/4/` is not a valid edit view URL, but still serves an edit page.
3. `~///en/organization/edit/composition/76cd0d81-1c70-4630-bf8b-5876868942ee/4/` redirects to valid edit view in `1.` above
4. `~////en/organization/edit/composition/76cd0d81-1c70-4630-bf8b-5876868942ee/4/`  redirects to valid edit view in `1.` above
5. `~////en/organization/edit/composition/76cd0d81-1c70-4630-bf8b-5876868942ee/4/`  serves an error.

I think that anything other than a single forward slash should serve an error - are there better/safer ways to handle this?

**Comment by jeancochrane** [comment]
Weird! I've never seen this before, but I can confirm that our other Django apps behave the same way (>4 slashes result in an error). A cursory Google search doesn't reveal a whole lot about what's going on here. It may be behavior in the Django URL parser layer, in the Nginx layer, or at the browser layer -- I'd have to do more investigation to figure out which one.

What's the safety concern around this behavior? Is there a situation where the redirects could cause a problem for a user?

**Comment by tlongers** [comment]
> What's the safety concern around this behavior? Is there a situation where the redirects could cause a problem for a user?

I don't have a good answer to this I'm afraid - I just found it unusual, and I don't know if it's harmful. My initial thoughts were about an access control bypass but this is unfounded. Googling around, this thread is [quite informative](https://stackoverflow.com/questions/10161177/url-with-multiple-forward-slashes-does-it-break-anything) about the the problem. Extra forward slashes seem to be allowed with respect to FPC  URL specifications and can be harmless _if_ the server gives the presence of extra slashes no particular meaning. The discussion there also focusses on rewrite and caching issues that the extra slashes might cause. Anything spring to mind with respect to the app's functioning in those areas?

**Comment by jeancochrane** [comment]
Thanks, that SO thread helps clarify some things for me!

In terms of forward-slash semantics, my interpretation is that we're safe as long as we don't define any routes where we expect users to be able to send empty URL parameters. As far as I can tell this is current behavior, and is also the default behavior for Django. I feel confident that we won't change this expectation in the future.

In terms of caching, I think the fact that the extra forward slashes will redirect to the single-slash URL means that the single-slash URL should continue to be the canonical one, so users should see the cached page we expect. If the extra slashes didn't redirect I might be concerned about caching and SEO.

Does this match your intuition on the situation? If it does, my instinct is to leave this behavior as-is and revisit it if we notice a case where it's doing something unexpected like throwing a 500 instead of 404 or not redirecting appropriately.

**Comment by tlongers** [comment]
Okay, that's clearer. At least it's something we're aware of now! Good to close?

**Comment by jeancochrane** [comment]
Good by me!
