### ISSUE TITLE
Adding source to empty field in incident record throws server error

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#627]
I found a validation issue, maybe related to PR https://github.com/security-force-monitor/sfm-cms/pull/612

1. Create a new incident
2. Add some text to  `Description`.
3. Associate a source with `Description`.
4. Navigate to `Start date` but don't enter a value.
5. Associate a source with `Start date`.
6. Save the record. 

Server throws an error.

**Comment by jeancochrane** [comment]
The issue here actually extends a bit deeper than incidents. When we clean fields for all Create forms, we determine which fields need to be saved by taking the union of fields that have values (`self.update_fields`) and fields that have sources (`sources_sent`):

https://github.com/security-force-monitor/sfm-cms/blob/8269ffa194092d616b9c882fc8fbf4ccde1dd497/sfm_pc/forms.py#L455-L457

This means that if a non-required field was assigned a source but doesn't have a value, we'll save it as an empty string instead of a null value in the database. In this particular case, the end result is that the incident has a `ViolationStartDate` with the value of the empty string `''`. When we go to update the search index, our date formatting code complains because it can't parse an empty string.

There are two ways we could fix this:

1. Quick bandaid: Update `make_search_index` to return null dates if it can't properly parse the date here:

https://github.com/security-force-monitor/sfm-cms/blob/8269ffa194092d616b9c882fc8fbf4ccde1dd497/search/management/commands/make_search_index.py#L727-L731

2. Deeper fix: Sort out why we're using a union operator here to store fields that have no values but have sources, and if it's true that this is a mistake, update the global field validation code to throw a `ValidationError` if the user provides a source but not a value for a non-required field (related to #598).

**Comment by tlongers** [comment]
Thanks @jeancochrane. These thoughts come to mind:

- Elsewhere, do you think the app may be relying on there being an empty string rather than a null value? 
- As a validation pattern, might it be useful to make the user actively specify if a field is empty, rather than infer it from the absence of a value? 

My view is to bandaid for now, and return to this if we have time after dealing with the bigger challenges in [Iteration 1: Squash blockers](https://github.com/security-force-monitor/sfm-cms/projects/4).

**Comment by jeancochrane** [comment]
> Elsewhere, do you think the app may be relying on there being an empty string rather than a null value?

Great question. I doubt we would have designed it this way; in my opinion the bigger risk is that there are more cases like this one lurking around where we're parsing the output of `Model.get_value()` and assuming that nulls and empty strings are both falsey as they are in Python, when in fact in `complex_fields` empty strings are truthy.

> As a validation pattern, might it be useful to make the user actively specify if a field is empty, rather than infer it from the absence of a value?

I'm not totally sure I follow. Is the idea that we might have all fields be required by default, and add in an additional interface for allowing a user to assert that a value really is null? If that's the case, then "leave the field blank, but add a source" seems like actually a pretty good UI for actively specifying an empty field. The natural follow-up question is whether it's plausible in your research workflow for a source to lead the researcher to want to put an empty value in a field, as opposed to an empty value indicating that there isn't a good enough source for the information in question.

> My view is to bandaid for now, and return to this if we have time after dealing with the bigger challenges.

Agreed!

**Comment by jeancochrane** [comment]
Started applying the bandaid here until I realized that allowing the search index to update will ultimately result in the same bug as https://github.com/security-force-monitor/sfm-cms/issues/598. 

Are we comfortable applying the fix @tonysecurityforcemonitor approved in https://github.com/security-force-monitor/sfm-cms/issues/598#issuecomment-522106011? Ultimately I think it's a stronger solution than allowing this behavior to proceed, but before doing so we need to have consensus that we don't want to support empty fields with sources attached to them.

**Comment by tlongers** [comment]
Concerns deprecated feature; closing.
