### ISSUE TITLE
Where no chain of command section exists, remove sidebar item

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#634]
Currently, where an upwards chain of command exists in the data, a "Chain of Command" section is correctly generated for that person. However, where that doesn't exist, the menu item is still displayed:

![image](https://user-images.githubusercontent.com/2115933/64609065-f1c7d700-d3c3-11e9-977a-04591024e6af.png)

**Comment by jeancochrane** [comment]
The issue here was actually specific to cases where an entity had a downards chain of command but not an upwards one. In those cases, we were correctly hiding the `Chain of command` div on the page, but neglecting to the hide the menu links as well.

I went ahead and pushed 8269ffa194092d616b9c882fc8fbf4ccde1dd497 directly to `master` since it was a one-line change. I confirmed this fixed the test person linked above (https://back.securityforcemonitor.org/en/person/view/186a4ce0-58ce-4756-ac68-081111dfd19f/). Do you want to do any more validation on this issue @tlongers?

**Comment by tlongers** [comment]
Thanks Jean, that's great. Fix confirmed.
