### ISSUE TITLE
Memberships can only be edited from the org that is a member 

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#635]
When editing an organization record if that organization has members, these are not showing up in the relationship tab for that organization. The membership shows up in the read only view however. For example, "Test Org 1" is a member of "Membership org 1":

![image](https://user-images.githubusercontent.com/2115933/64620720-52630e00-d3dc-11e9-9f43-7375cadb77c3.png)

However, if we look the relationships of "Membership org 1" we do not see this reflected:

![image](https://user-images.githubusercontent.com/2115933/64620885-9a823080-d3dc-11e9-8f64-d5aa4466ddb9.png)

Not sure if this is a bug or feature - do we want memberships to be editable from both sides of the relationship, or only from within the context of the orgs that are members of the other org?

**Comment by jeancochrane** [comment]
From a UI perspective, I like the idea of having memberships be editable from both sides of a relationship. It's nice to be able to audit all relationships pertaining to an entity from the edit view, particularly when deleting an entity.

I'm guessing that we don't currently support this because a full implementation would require a refactor of the Create Membership form in addition to the display table. There's a lot of custom logic in the Create Composition form that tries to figure out if the user is creating a Parent or Child relationship, for example, and we'd need to have similar logic for the membership form in order to allow them to be fully bidirectional. IIRC the Composition logic isn't super clean so we'd probably want to put some elbow grease into rationalizing it and having both forms share some similar logic.

All that being said, we could probably get a quick and easy solution by having the Edit button link out to the form from the other side of the relationship in the case where the user is editing the member org. In that situation the form wouldn't really be bidirectional, and we might risk confusing the user by technically punting them over to an edit view for a different entity, but it would allow us to display all of the memberships on a single entity edit page.

What do you think @tlongers?

**Comment by tlongers** [comment]
Concerns deprecated feature; closing.
