### ISSUE TITLE
Importer assigns too many sources to certain entities

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#637]
@tlongers noticed that some postings have too many sources. For example, the following posting has 9 sources for the `membershipperson:organization` attribute in the source spreadsheet, but WWIC displays 43:

https://back.securityforcemonitor.org/en/person/edit/postings/63ec211d-ef4d-4588-8464-b9e1013e6735/1012/

After some debugging, I'm pretty confident that the importer is responsible for this discrepancy. The root of the problem is the way that we handle some variables representing sources. In the case of postings, we create a `sources` variable by retrieving the sources for `organization:name` in the spreadsheet:

https://github.com/security-force-monitor/sfm-cms/blob/6e293cdee376738219e405d6641b524f6f313399/sfm_pc/management/commands/import_google_doc.py#L1612

We use this variable to set the base sources for both the organization (if we need to create one) and for the posting:

https://github.com/security-force-monitor/sfm-cms/blob/6e293cdee376738219e405d6641b524f6f313399/sfm_pc/management/commands/import_google_doc.py#L1617-L1628

https://github.com/security-force-monitor/sfm-cms/blob/6e293cdee376738219e405d6641b524f6f313399/sfm_pc/management/commands/import_google_doc.py#L1667-L1678

The key problem is that **we expect the values associated with the `'sources'` keys to be copies of the `sources` variable, but in fact they are mutable references to the variable itself.** This means that when we go to add more sources to the `organization:name` attribute later, we wind up accidentally adding these sources to every dict that referenced the `sources` variable:

https://github.com/security-force-monitor/sfm-cms/blob/6e293cdee376738219e405d6641b524f6f313399/sfm_pc/management/commands/import_google_doc.py#L1648-L1649

Since `org_info["Organization_OrganizationName"]['sources']` is a direct reference to the `sources` variable, and not a copy of the data, appending the elements of `name_sources` to this value will also mutate any other dictionary that referenced the `sources` variable.

The right move here is to change these dictionaries to reference shallow copies of `sources` instead of referencing `sources` itself. Since the importer code more broadly tends to share the `sources` variable and use direct references instead of copies, we should probably update the rest of the importer code to follow this new pattern, too. @tlongers had talked about creating some sample data to verify this behavior; having this kind of data would make this change much easier, and would even allow us to potentially unit test it.

**Comment by tlongers** [comment]
Quick update on this issue. I've developed a first cut of testing data. The tests are all positive, ideal cases rather than deliberately failing tests. They do the following:

- creates four units and relates them in a simple vertical organizational tree.
- creates four persons and posts them to each of the four above units, to create a command structure sufficient to populate the Chain of Command chart.
- creates two units and creates a membership relation between them
- for all the above, each datapoint created for units and persons has a unique source/access points, the title of which indicates what datapoint it evidences, what the value should be, and what confidence value we should expect. This should enable us to spot sources that are mismatched.

Based on whether or not this approach proves helpful, I will extend the range of objects and scenarios that we test through this method.

**Comment by tlongers** [comment]
I see that https://github.com/security-force-monitor/sfm-cms/pull/644 is merged into master. Before closing this, we should re-run the importer on the staging instance and verify the fix against it.

**Comment by tlongers** [comment]
Likely resolved.
