### ISSUE TITLE
Question: uniqueness of Source Publication Title data

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#648]
The import sheets have a set of fields for us to record a unique publication name. They were set up when we were deduplicating the source data, and still give us a useful QA measure to keep publications distinct:

- `country` e.g `Nigeria`

- `key` e.g. `NigeriaDaily Trust` (this is a straight concatenation of `country` and `publication_title`.

- `publication_title` e.g `Daily Trust`

- `new_pub_id` e.g. `ffc4fc8e-45e1-4ddb-9faa-55c7e16f81ee`. A UUID, assigned manually, to designate a distinct publication.

The outcome of this is that we can assure that publications with the same time in different countries are treated as different. Behind the scenes, does the importer use any of this logic to ensure that `The Guardian` newspapers of the UK and Nigeria are kept distinct? It looks like this is the case, but good to be sure.

**Comment by jeancochrane** [comment]
The source code for the [`create_source()` method](https://github.com/security-force-monitor/sfm-cms/blob/98c430831ce9c5f842d32118150915d790018474/sfm_pc/management/commands/import_google_doc.py#L1474) seems to indicate that we use `country` and `publication_title` to determine distinct Sources, and we use `new_pub_id` to determine distinct AccessPoints. I don't believe we use `key`, although since it's a concatenation of `country` and `publication_title` I think we're probably covered already.

**Comment by tlongers** [comment]
Thank you, that's really helpful.

`new_pub_id` is a unique key for each distinct publication, but `country` and `title` will have the same effect. One thing though -  I am fairly sure (and hope!)  that `source_id` is is used to create access points though. For example, in our sheet `f4888dff-c139-4938-80b2-4d864725007f` is the `source_id` value for this row:

`"Stars on their shoulders. Blood on their hands. War crimes committed by the Nigerian military"`

`https://web.archive.org/web/20150910231307/https://www.amnesty.org/en/documents/afr44/1657/2015/en/` 

And this UUID is also used in the below

`~/en/source/view/3af97bf5-bf43-4432-bbc8-d464d4ca771c/f4888dff-c139-4938-80b2-4d864725007f/#evidence`

Can you double check this is the case?

**Comment by jeancochrane** [comment]
Yes, that's correct! My apologies, slip of the fingers. To be specific, `lookup_source_id` is the field we use to create AccessPoints. We don't currently use `new_pub_id` because Publications aren't actually stored as separate entities in the database yet, although my understanding is we'd like to do so at some point in the future.

**Comment by tlongers** [comment]
Phew :) Thanks for the answers; very helpful and clarifying. Closing this now.
