### ISSUE TITLE
Update the importer for field harmonization

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#658]
Update the importer to prepare for field harmonization, including:

1. Refactor the code to accept field names instead of column positions
2. Update, add, or remove fields as appropriate
3. Test and troubleshoot the updated import

Tom and Tony will share new data that we can run through the importer to test this. The new testing framework for the importer should also be useful here.

**Comment by tlongers** [comment]
Something that isn't clearly documented in the field harmonization sheet is that all import sheets containing entity data now have an [ISO 3166-1 two letter country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Decoding_table) prefix. For example, the Mexico sheet instead of `units` the sheet is called `mx_units`, and so on for other entities.

**Comment by tlongers** [comment]
Superceded by #714 and #704. Closing.
