### ISSUE TITLE
Move WWIC translations to Transifex?

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#671]
I've integrated Transifex as the translation management platform for the Research Handbook.

The positives I can see:
- well developed UX for translation.
- translation memory (helpful for long term projects).
- apparently seamless integration with Read The Docs (after a little finagling).
- easy to expose the translation process to the public/community, or to a commercial translator.

Downsides:
- need to allocate time to coordinate and quality check the community aspect (if we choose to do that).
- big pricing ramp-up for anything private.
- another set of tools to manage/keep abreast of.

Currently we use Rosetta to manage translations of WWIC, but would it make sense to move it to Transifex? Thoughts on or experience of Transifex @jeancochrane @tonysecurityforcemonitor ?

**Comment by jeancochrane** [comment]
Nice! I haven't used Transifex but I really like the look of the UI. I love that Rosetta is FLOSS, but I admit that the UI isn't very friendly, especially to non-technical users. Transifex seems like it could make sense, especially if you're planning to ramp up translation work in the future.

Looks like Transifex has some [pretty clear docs on integrating with the Django i18n translation system](https://docs.transifex.com/integrations/django#localizing%C2%A0with-django). The main change would be that we would start using GitHub as the source of truth for .po files instead of the live files on the server, and we would use Transifex to update those files in GitHub. I actually think this could be a way more stable approach than our current one so I'd be excited to move in that direction.

I'd estimate somewhere around 4 hours to set this up, to give us some time to deal with the inevitable confusion of a new integration.

**Comment by tlongers** [comment]
Thanks for the appraisal Jean, and the estimatation of the work involved. Over the next few weeks, I'm going to gain a little experience of the Transifex mechanism in the context of the Research Handbook, and then will return and make a decision on whether to use it for WWIC.

**Comment by tlongers** [comment]
Challenging though Rosetta is, it _just works_ in an uncomplicated way. Closing issue.
