### ISSUE TITLE
Add country selector to front page

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#687]
Currently, we have a item on the frontpage that doesn't provide the information it links to:

<img width="929" alt="image" src="https://user-images.githubusercontent.com/2115933/83160001-8e6f0800-a0fe-11ea-8b08-13b88b965e10.png">

As the `~/countries` page no longer exists, this links to `~/about`, which doen't contain a list of countries. So it's strange for users.

Better to replace it with a filter on the search results:

<img width="607" alt="image" src="https://user-images.githubusercontent.com/2115933/83161520-726c6600-a100-11ea-9056-2f79185bfe8e.png">

@jeancochrane I think this should be fixed, though it's strictly out of the scope. What's the dev and implementation effort for it?

**Comment by jeancochrane** [comment]
Great catch! The technical lift here would just be to add a Solr query to the homepage view that returns the set of countries in the index, and use it to populate a new form element. From start to deployment I think we could do it in 1-2 hours.

**Comment by tlongers** [comment]
That's fine; let's do it as soon as possible. We can also provide the localisation strings.

**Comment by jeancochrane** [comment]
@tlongers Great, we'll have a fix up this week.

**Comment by jeancochrane** [comment]
@tlongers #688 brought a draft of this feature to staging. Since there are actually quite a few country values in the search index and not all of them are sensible, I decided instead to base the options on the [`OSM_DATA`](https://github.com/security-force-monitor/sfm-cms/blob/5988de96da685a7738bacc827a2a4fc418a27094/sfm_pc/settings.py#L239) config dictionary that we use to determine which countries should have OSM data loaded. Let me know how it looks to you!

**Comment by tlongers** [comment]
I like it - it adds a nice new dimension.  Some thoughts:
- there are values  OSM_DATA for which there will be no data, or perhaps staging has some additional values on it from other testing processes? (e.g. Burkina Faso?)
- I think the issue with using the search index to provide the list is that it includes country values attached to sources, which is a much larger list than the available data. The another possible way to filter this out and get a clean country list, and if the OSM_DATA quibble I have above becomes an issue, would be to select country values only where `unit` records exist. 
- The values in the drop down values should be sorted alphabetically.
- the styling needs a bit of attention: the dropdown isn't visually consistent with the dropdown for languages, and the height seems out of place with that of the main search box and the entity selectors  Any thoughts on making it fit together a little better?

**Comment by jeancochrane** [comment]
Thanks for the feedback on this! Some thoughts:

> * there are values OSM_DATA for which there will be no data, or perhaps staging has some additional values on it from other testing processes? (e.g. Burkina Faso?)
> * I think the issue with using the search index to provide the list is that it includes country values attached to sources, which is a much larger list than those for units, persons and incidents . The another possible way to filter this out and get a clean country list, and if the OSM_DATA quibble I have above becomes an issue, would be to select country values only where unit records exist.

This makes sense. I'll see if retrieving the values from the search index but restricting it to values tied to units gives us a more sensible list. At minimum we can always hard-code the list of countries, as we did with the old Countries page, but I figured it might be handy to not have to remember to update that every time we add a batch of data for a new country.

> The values in the drop down values should be sorted alphabetically.

Can do 👍 

> the styling needs a bit of attention: the dropdown isn't visually consistent with the dropdown for languages, and the height seems out of place with that of the main search box and the entity selectors Any thoughts on making it fit together a little better?

Good catch here, it looks like the language selector is Select2 enabled but the country selector is not, which contributes to the style mismatch. That's an easy fix. The height is a bit of a different story. Were you hoping that it would be precisely the same height as the entity selector buttons? If so I can look into it and see if we can add a CSS rule to enforce that.

**Comment by tlongers** [comment]
>This makes sense. I'll see if retrieving the values from the search index but restricting it to values tied to units gives us a more sensible list. At minimum we can always hard-code the list of countries, as we did with the old Countries page, but I figured it might be handy to not have to remember to update that every time we add a batch of data for a new country.
Thanks, and yes to doing antyhing we can to avoid yak-shaving :)

> Were you hoping that it would be precisely the same height as the entity selector buttons?
I think so. It needs to be visually clear to users that it's part of the same set of switches that will impact on the results once `search` is selected.

**Comment by tlongers** [comment]
For info, I've added in the translation strings for Spanish and French.

**Comment by jeancochrane** [comment]
Just merged an update to the staging site that:

- Populates the country selector from the search index instead of the OSM_DATA config variable
- Sorts the options alphabetically
- Adjusts the height to match the entity selector buttons

We're also now caching the homepage to avoid hitting the search index on every request. Let me know how it looks!

**Comment by tlongers** [comment]
It looks very good Jean 👍  - nice work.

Additional question: how do we localize the values in the dropdown?

**Comment by jeancochrane** [comment]
> Additional question: how do we localize the values in the dropdown?

Extremely good question, I apologize for not thinking to raise it sooner. My understanding is that we're not translating anything in the search index right now, which means that across the site we're using English names for countries. Is that your understanding too? If so, do we still want to localize the dropdown? If we do, I think we'll need to hard-code the list of available countries in a config variable so we can mark the values for translation, instead of retrieving them dynamically from the search index.

**Comment by tlongers** [comment]
If we hard-coded it for the front page, it would lead to an odd mismatch with the behaviour of the list in the country facet that appears in search results, which is drawn from the search index. What's the overhead to work with solr to enable this. Perhaps it is time for us to consider how to add multi-lingual data elements as well.

**Comment by jeancochrane** [comment]
> If we hard-coded it for the front page, it would lead to an odd mismatch with the behaviour of the list in the country facet that appears in search results, which is drawn from the search index. What's the overhead to work with solr to enable this. Perhaps it is time for us to consider how to add multi-lingual data elements as well.

I've never done multilingual search before, so I would have to do some more in-depth research before being able to provide a reliable estimate. A quick search reveals that there isn't an obvious way to do it like turning a flag on or off, so I suspect it would be a task in the 20-40 hour range. The best resource I could find was this guide on [Handling a multi-language search](https://subscription.packtpub.com/book/big_data_and_business_intelligence/9781783981847/1/ch01lvl1sec10/handling-a-multilingual-search), which suggests the following approaches:

> - **Use one Solr field for each language**: This is a simple approach that guarantees that the text is processed the same way as it was indexed. As different fields can have separate analyzers, it is easy to handle multiple languages. However, this increases the complexity at query time as the input query language needs to be identified and the related language field needs to be queried. If all fields are queried, the query execution speed goes down. Also, this may require creation of multiple copies of the same text across fields for different languages.
>
> - **Use one Solr core per language**: Each core has the same field with different analyzers, tokenizers, and filters specific to the language on that core. This does not have much query time performance overhead. However, there is significant complexity involved in managing multiple cores. This approach would prove complex in supporting multilingual documents across different cores.
>
> - **All languages in one field**: Indexing and search are much easier as there is only a single field handling multiple languages. However, in this case, the analyzer, tokenizer, and filter have to be custom built to support the languages that are expected in the input text. The queries may not be processed in the same fashion as the index. Also, there might be confusion in the scoring calculation. There are cases where particular characters or words may be stop words in one language and meaningful in another language.

Since we want to display as well as index the text, it sounds like the best option is using one Solr field for each language. The rough set of tasks I can imagine here would be:

- Create new duplicate fields in the index for each language (e.g. `adminlevel1_fr` and `adminlevel1_es`)
- Add new columns to the import sheet representing these translated values (ideally we would do this through Rosetta but I can't find any resources about how to make that work)
- Update the models to mark these fields as translated (which I understand is supported in `complex_fields` through the [`@translated` decorator](https://github.com/security-force-monitor/complex_fields/blob/328aef79a458fb568f9917929f9817c8c73f729c/complex_fields/model_decorators.py#L11-L13) although I haven't used it yet)
- Update the import script to save the translated field values
- Update `make_search_index` script to save translated values to the language-specific search index fields
- Update the frontend search interface to show different facets depending on the user's language

**Comment by tlongers** [comment]
Quick note - I think this PR has broken the  front page template for logged-in users: if you log in, you can't see the data creation options on the front page but they appear on the others.

**Comment by jeancochrane** [comment]
Good catch @tlongers, I opened up https://github.com/security-force-monitor/sfm-cms/issues/694 to fix that bug.

**Comment by tlongers** [comment]
Closing the issue, though the discussion here will have relevance to current work on model translations that is ongoing at time of writing.
