### ISSUE TITLE
Update app and server dependencies

### ISSUE THREAD

**Issue by jeancochrane** [security-force-monitor/sfm-cms#707]
At this point the app dependencies are quite out of date. Let's update them to the most recent versions. High priority packages include:

* Python
* [Django dependencies](https://github.com/security-force-monitor/sfm-cms/blob/master/requirements.txt)
* Postgres
* Solr (consider updating to the most recent minor version instead of a major version update)

The actual updating here should be easy, but we'll want to QA the import, indexing, search, and browsing interfaces to make sure that everything still works, in addition to confirming that the test suite continues to pass. We'll also need to factor in time for updating service-level packages on the staging server, the Sahel instance, and the production server.

**Comment by tlongers** [comment]
@hancush was part of this implemented during the shift to Haystack?

**Comment by hancush** [comment]
@tlongers Part, but not all.

**Comment by tlongers** [comment]
Does completing this have an easily defined "To Do"?

**Comment by hancush** [comment]
@tlongers Easy to define, with varying levels of difficulty to implement. Here's how I'd attack it:

- [ ] **Upgrade Python.** We're currently running on a deprecated version of Python 3.5. Many of our app dependencies cannot be upgraded until we upgrade Python, so it makes sense to do this first. It's a bit challenging, because we'll have to upgrade Python on all of our active servers.
- [ ] **Upgrade app dependencies.** We're running a deprecated version of Django that's two major versions behind the latest release, which has a ripple effect on the third-party Django plugins we rely on, as well. It is increasingly difficult to develop the app around these obsolete core dependencies. Upgrading our app dependencies may require some code changes to address any API / feature changes in newer versions of our dependencies, but we only need to make the changes once – they'll be applied to all of our instances as we deploy them – and they will improve the developer experience, making changes easier and more cost effective.
- [ ] **Upgrade Postgres.** We're 4 major versions behind the latest Postgres release. Our version, 9.6, is still supported but will reach end of life in November, so it would behoove us to upgrade. Like Python, we'll need to upgrade this dependency on all of our active servers.
- [ ] **Upgrade Solr.** If, as Jean noted, we don't want to upgrade major versions, I'd want to look more closely at what we'd get upgrading to the latest minor release in the 6.x series before upgrading Solr, as it, too, would require an upgrade across all servers, with potentially sticky changes in behavior to important features we use, such as date range filtering powering the command charts.

**Comment by tlongers** [comment]
Thanks for the rundown. We'll return to this for the next milestone I think.

**Comment by hancush** [comment]
This is done!
