### ISSUE TITLE
Heroku - additional deploy parameters

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#754]
Here's a few extra thoughts to consider with respect to commencing work on migrating WWIC's deployment from AWS to Heroku (see #710). I think they're maybe naive, and possibly not dev issues per se (but rather logical infrastructure stuff). Anyhow, throwing them out there:

Needs:

- Spin up an instance of WWIC that can only be accessed by specified users
- Ensure that instance cannot be detected by crawlers/bots/others and remains incognito online 

Initial thoughts:

- at the deployment server level devise and tempate a number of basic access control measures that could range from simple httaccess, or IP address/range checks/MAC, or other server-based access restrictions (perhaps VPN only access).
- introduce much stronger monitoring and logging  activity on private instances that we have on the production WWIC. This would include at the least login activity user session behaviour. 
- in the app, use the existing access control functionality to make logins necessary to view any data on the private instance.

**Comment by hancush** [comment]
@tlongers Thanks for raising this! 

I think it would be fairly straightforward to implement a sitewide login and maintain a controlled list of users, and potentially even acceptable IP addresses for those users, for private instances of the site. We can also include directives to prevent crawlers from indexing the site (in any case, for private instances, all they would see is a log in screen). 

Monitoring would depend on how much detail you need. By default, Django provides information on the last login of users. If you need analytics beyond that, I'm not super familiar with Matomo, but I would guess we could tie browsing data to a user (or  some other useful identifier). 

All of these measures, though, are on the app side. There is also the data itself to consider. On AWS, we host our own Postgres instances. In the migration to Heroku, we would use their hosted Postgres solution, so the data would live on Heroku's servers, not one we control. 

Heroku maintains pretty robust [security](https://www.heroku.com/policy/security) and [compliance](https://www.heroku.com/compliance) practices for all of its environments, but it also offers private and "shield" tiers with additional security and compliance measures.

The "shield" tier is the only one offering health and payment data compliance, but WWIC does not touch either of those domains, so I think we can rule that out. The main advantage [of the private tier](https://devcenter.heroku.com/articles/dyno-runtime#private-spaces-runtime) is that it runs on its own network rather than shared infrastructure and offers some additional privacy controls. Note, though, that the cheapest private plan for Postgres is $300/month, quite a bit more than $50/month for a production tier instance on shared infrastructure. (And, if you wanted to spin up private instances with different data, you'd pay that for each instance.)

There is always the option to host data on AWS infrastructure (we've had success in the past with [RDS](https://aws.amazon.com/rds/)), however it would add a layer of complexity and, at our hourly rate, probably not amount to much, if any, savings vs. the monthly cost of a higher security tier of Heroku's hosted Postgres.

Can you say more about sensitivity of the data itself?

**Comment by tlongers** [comment]
Thanks for the helpful response Hannah.  I think we are limited, for now, to consideration of the the app-level items that we can implement. It's useful to know that we do have options to enhance protection using Heroku's Private Spaces Runtime if needed (and budget allows). This gives us something to consider should the need arise to deploy something that requires addition protections.

**Comment by hancush** [comment]
Related to #710. Closing, for now, since we are not proceeding with the Heroku migration.
