### ISSUE TITLE
Start and end dates in incident search results don't match corresponding dates on detail page

### ISSUE THREAD

**Issue by hancush** [security-force-monitor/sfm-cms#756]
For instance,

<img width="836" alt="Screen Shot 2021-05-12 at 3 19 19 PM" src="https://user-images.githubusercontent.com/12176173/118039051-828f4c80-b335-11eb-9384-6a733de14f56.png">
<img width="1241" alt="Screen Shot 2021-05-12 at 3 19 23 PM" src="https://user-images.githubusercontent.com/12176173/118039053-828f4c80-b335-11eb-81bc-075fa3ad4959.png">

https://whowasincommand.com/en/violation/view/7c080b1d-15cc-464e-80be-9f41ab44c6e9/

**Comment by tlongers** [comment]
Good catch. Here's the data that forms the basis of this record:

field | data
-- | --
incident:owner:admin | TW
incident:status:admin | 3
incident:comments:admin |  
incident:id:admin | 7c080b1d-15cc-464e-80be-9f41ab44c6e9
incident:start_date | 12/31/2015
incident:start_date_month | 12
incident:start_date_day | 31
incident:start_date_year | 2015
incident:end_date | 12/31/2015
incident:end_date_month | 12
incident:end_date_day | 31
incident:end_date_year | 2015
incident:pub_date | 9/5/2017
incident:pub_date_month | 9
incident:pub_date_day | 5
incident:pub_date_year | 2017
incident:update_date |  
incident:update_date_month |  
incident:update_date_day |  
incident:update_date_year |  
incident:update_status |  
incident:location_description | Montaza Police Station
incident:location | Alexandria (osm, point) 94859e3b-6fc0-43e2-88a6-bd6aaa2c2403
incident:violation_type | Beating
incident:violation_description | According to Human Rights Watch: "Around a month later, on December 31,[...truncated so we can display it in the issue]
incident:perpetrator_person_id:admin |  
incident:perpetrator_person_name |  
incident:perpetrator_unit_id:admin |  
incident:perpetrator_unit_name |  
incident:perpetrator_classification | Police
incident:all:source | 9ee2808b-658e-41b3-a678-6351e71de29b

Comparing this to the record and search view on WWIC I can see the below:
- the data on the unit is correct, and the details in the search results are not.
- that because the start date and end date of the incident are the same, the title on the unit record has been correctly parsed into a single date (unlike, for example, on this other incident from Egypt where correctly WWIC shows a date range in the incident title because the dates differ).
- Looking at the data in the search view, the month and year is correct: the problem is with the days. The day value repeats the number of the month, so we have 10 October, 3 March and 12 December. 

The dates must be correctly parsed into the database, or they would be incorrect in the record view. So, it looks to me like a date format issue in how the dates are displayed in the search results table. Is it possible this is linked to #721?

**Comment by hancush** [comment]
> So, it looks to me like a date format issue in how the dates are displayed in the search results table.

You were spot on, @tlongers! Putting a patch in now.
