### ISSUE TITLE
Sources with Page numbers

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#76]
@evz @tlongers going through the error log for sources for organizations there were a couple of sources (Policing Nigeria in the 21st Century, Criminal Force, and Police Station Visitor Week) where the importer had an issue - and I saw that they all had a page number attached to them. 

I know we discussed this #73 --- but I realized that my proposed solution of putting the page number in the title might be a bad one. Would it mean that every time we entered a different page number for the same source the CMS would treat it as a different source? It seems like it would require a lot of re entry of data from the researcher - which increases the chance of incorrect data entry (I'm seeing slight variations on how the Criminal Force report was entered for instance).

I am now thinking that adding a non-required field for page number would be a much better solution - so the overall source information (title, publication, country, date of publication, etc.) would remain the same, it would just be the page number that would be different. However, I don't know if this is a relatively straightforward thing to implement or if its creating a hairy problem.

**Comment by evz** [comment]
Database changes like this are pretty easy to handle, especially if you are adding a column that is not required. I'll go ahead and add this.

**Comment by tlongers** [comment]
There must be some well-used citation subformat/widget thing that we can simply pull in here rather than ad-hoc'ing it?

**Comment by evz** [comment]
@tlongers There certainly are citation subformats and a cursory googling turns up at least one, relatively simple to use, package for standardizing and displaying citation information. Implementing something like that right now would be a pretty big change because of the way that every single field on every single model has an associated source and this would basically represent swapping what's in place for this. Maybe we can consider this for a future date? I think it would really save a lot of headaches down the road.

For right now, I can add columns to the existing tables. It looks like with this and #89, I should add a page number field and an accessed date field? Both not required?
